#!/usr/bin/env python3
"""
Bake Linter - Command Line Interface.

A production-grade linter for Yocto/OpenEmbedded recipes.

Usage:
    bake-linter [OPTIONS] PATHS...
    
Examples:
    bake-linter recipes/
    bake-linter --format json meta-layer/
    bake-linter --enable LICENSE001,MANDATORY001 --disable STYLE001 .
    bake-linter --ci --output report.json recipes/
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Optional, TextIO

from bake_linter import __version__
from bake_linter.config import LinterConfig
from bake_linter.core.engine import LintEngine
from bake_linter.core.models import ExitCode
from bake_linter.core.registry import get_registry
from bake_linter.output.text import TextFormatter, CompactTextFormatter
from bake_linter.output.json_output import JsonFormatter, JsonLinesFormatter
from bake_linter.output.html import HtmlFormatter


def create_parser() -> argparse.ArgumentParser:
    """Create the argument parser."""
    parser = argparse.ArgumentParser(
        prog="bake-linter",
        description="Production-grade linter for Yocto/OpenEmbedded recipes",
        epilog="For more information, see: https://github.com/99ecarvalho/bake_linter",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    
    # Version
    parser.add_argument(
        "--version", "-V",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    
    # Paths to lint
    parser.add_argument(
        "paths",
        nargs="*",
        type=Path,
        default=[Path(".")],
        help="Files or directories to lint (default: current directory)",
    )
    
    # Config file
    parser.add_argument(
        "--config", "-c",
        type=Path,
        help="Path to configuration file",
    )
    
    # Rule selection
    rule_group = parser.add_argument_group("rule selection")
    rule_group.add_argument(
        "--enable", "-e",
        type=lambda s: s.split(","),
        metavar="RULES",
        help="Enable specific rules (comma-separated, e.g., LICENSE001,MANDATORY001)",
    )
    rule_group.add_argument(
        "--disable", "-d",
        type=lambda s: s.split(","),
        metavar="RULES",
        help="Disable specific rules (comma-separated)",
    )
    rule_group.add_argument(
        "--enable-group",
        type=lambda s: s.split(","),
        metavar="GROUPS",
        help="Enable all rules in groups (comma-separated)",
    )
    rule_group.add_argument(
        "--disable-group",
        type=lambda s: s.split(","),
        metavar="GROUPS",
        help="Disable all rules in groups (comma-separated)",
    )
    
    # Output format
    output_group = parser.add_argument_group("output options")
    output_group.add_argument(
        "--format", "-f",
        choices=["text", "compact", "json", "jsonl", "html"],
        default="text",
        help="Output format (default: text)",
    )
    output_group.add_argument(
        "--output", "-o",
        type=Path,
        metavar="FILE",
        help="Write output to file instead of stdout",
    )
    output_group.add_argument(
        "--html-report",
        type=Path,
        metavar="FILE",
        help="Generate HTML report to file (in addition to primary output)",
    )
    
    # Verbosity
    verbosity_group = parser.add_argument_group("verbosity")
    verbosity_mutex = verbosity_group.add_mutually_exclusive_group()
    verbosity_mutex.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Show detailed output including context",
    )
    verbosity_mutex.add_argument(
        "--quiet", "-q",
        action="store_true",
        help="Suppress non-error output",
    )
    
    # CI mode
    ci_group = parser.add_argument_group("CI integration")
    ci_group.add_argument(
        "--ci",
        action="store_true",
        help="CI-friendly mode (no colors, strict exit codes)",
    )
    ci_group.add_argument(
        "--no-color",
        action="store_true",
        help="Disable colored output",
    )
    ci_group.add_argument(
        "--warnings-as-errors",
        action="store_true",
        help="Treat warnings as errors (exit code 1 for warnings)",
    )
    
    # Filtering
    filter_group = parser.add_argument_group("filtering")
    filter_group.add_argument(
        "--include-autogenerated",
        action="store_true",
        help="Include autogenerated files (normally skipped)",
    )
    
    # Informational
    info_group = parser.add_argument_group("information")
    info_group.add_argument(
        "--list-rules",
        action="store_true",
        help="List all available rules and exit",
    )
    info_group.add_argument(
        "--list-groups",
        action="store_true",
        help="List all rule groups and exit",
    )
    info_group.add_argument(
        "--show-config",
        action="store_true",
        help="Show effective configuration and exit",
    )
    
    return parser


def list_rules() -> None:
    """Print all available rules."""
    registry = get_registry()
    registry.discover_rules()
    
    rules = registry.get_all_rules()
    
    print(f"Available rules ({len(rules)}):\n")
    print(f"{'Rule ID':<15} {'Severity':<10} {'Enabled':<8} {'Name'}")
    print("-" * 70)
    
    for rule_id in sorted(rules.keys()):
        rule_cls = rules[rule_id]
        severity = rule_cls.default_severity.name.lower()
        enabled = "yes" if rule_cls.enabled_by_default else "no"
        print(f"{rule_id:<15} {severity:<10} {enabled:<8} {rule_cls.name}")
    
    print(f"\nGroups: {', '.join(sorted(registry.get_all_groups()))}")


def list_groups() -> None:
    """Print all rule groups."""
    registry = get_registry()
    registry.discover_rules()
    
    groups = registry.get_all_groups()
    
    print(f"Available rule groups ({len(groups)}):\n")
    
    for group in sorted(groups):
        rules = registry.get_rules_by_group(group)
        rule_ids = [r.rule_id for r in rules]
        print(f"  {group}: {', '.join(sorted(rule_ids))}")


def show_config(config: LinterConfig) -> None:
    """Print effective configuration."""
    import json
    print(json.dumps(config.to_dict(), indent=2))


def get_formatter(format_name: str, color: bool, verbose: bool, output: TextIO):
    """Get the appropriate formatter."""
    formatters = {
        "text": lambda: TextFormatter(output=output, color=color, verbose=verbose),
        "compact": lambda: CompactTextFormatter(output=output, color=False, verbose=verbose),
        "json": lambda: JsonFormatter(output=output, verbose=verbose),
        "jsonl": lambda: JsonLinesFormatter(output=output, verbose=verbose),
        "html": lambda: HtmlFormatter(output=output, verbose=verbose),
    }
    return formatters[format_name]()


def main(argv: Optional[List[str]] = None) -> int:
    """Main entry point."""
    parser = create_parser()
    args = parser.parse_args(argv)
    
    # Handle informational commands
    if args.list_rules:
        list_rules()
        return ExitCode.SUCCESS
    
    if args.list_groups:
        list_groups()
        return ExitCode.SUCCESS
    
    # Load configuration
    try:
        config = LinterConfig.load(args.config)
    except (FileNotFoundError, ValueError) as e:
        print(f"Configuration error: {e}", file=sys.stderr)
        return ExitCode.RUNTIME_ERROR
    
    # Merge CLI arguments
    config.merge_cli_args(
        enable=args.enable,
        disable=args.disable,
        enable_groups=args.enable_group,
        disable_groups=args.disable_group,
        output_format=args.format,
        output_file=str(args.output) if args.output else None,
        verbose=args.verbose,
        quiet=args.quiet,
        color=not args.no_color,
        ci_mode=args.ci,
    )
    
    if args.show_config:
        show_config(config)
        return ExitCode.SUCCESS
    
    # Validate paths
    for path in args.paths:
        if not path.exists():
            print(f"Error: Path does not exist: {path}", file=sys.stderr)
            return ExitCode.RUNTIME_ERROR
    
    # Initialize engine
    engine = LintEngine()
    
    # Configure engine
    engine.configure(
        rule_configs=config.get_rule_configs(),
        enabled_rules=list(config.enabled_rules) if config.enabled_rules else None,
        disabled_rules=list(config.disabled_rules),
        enabled_groups=config.enabled_groups,
        disabled_groups=config.disabled_groups,
        skip_autogenerated=not args.include_autogenerated,
    )
    
    # Run lint
    try:
        results = engine.lint_files(args.paths)
    except Exception as e:
        print(f"Lint error: {e}", file=sys.stderr)
        return ExitCode.RUNTIME_ERROR
    
    summary = engine.get_summary()
    
    # Determine output destination
    output_file: Optional[TextIO] = None
    if args.output:
        output_file = open(args.output, "w", encoding="utf-8")
    
    try:
        output_stream = output_file or sys.stdout
        use_color = config.color and not args.ci and output_stream.isatty()
        
        # Format and output results
        if not config.quiet:
            formatter = get_formatter(
                args.format,
                color=use_color,
                verbose=args.verbose,
                output=output_stream,
            )
            formatter.write(results, summary)
        
        # Generate HTML report if requested
        if args.html_report:
            html_formatter = HtmlFormatter(verbose=args.verbose)
            html_formatter.write_to_file(results, summary, args.html_report)
            if not config.quiet:
                print(f"\nHTML report written to: {args.html_report}", file=sys.stderr)
    
    finally:
        if output_file:
            output_file.close()
    
    # Determine exit code
    exit_code = summary.get_exit_code()
    
    # Treat warnings as errors if requested
    if args.warnings_as_errors and exit_code == ExitCode.WARNINGS_FOUND:
        exit_code = ExitCode.ERRORS_FOUND
    
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
