# -*- coding: utf-8 -*-
"""
Configuration system for the Bake Linter.

Supports loading configuration from YAML/JSON files and merging with CLI options.
CLI options always take precedence over config file settings.

(c) 2024-2026 Eduardo Correia <ecorreia@apliant.com.br>
All rights reserved.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Dict, List, Any, Optional, Set

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

from bake_linter.core.models import RuleConfig, Severity


# Default configuration file names (searched in order)
CONFIG_FILENAMES = [
    ".bake-linter.yaml",
    ".bake-linter.yml",
    ".bake-linter.json",
    "bake-linter.yaml",
    "bake-linter.yml",
    "bake-linter.json",
]


class LinterConfig:
    """
    Configuration container for the Bake Linter.
    
    Handles loading configuration from files, environment variables,
    and command-line arguments with proper precedence:
    
    1. CLI arguments (highest priority)
    2. Environment variables
    3. Config file
    4. Built-in defaults (lowest priority)
    
    Example config file (YAML):
        rules:
          LICENSE001:
            enabled: true
            severity: error
          STYLE001:
            enabled: false
        
        settings:
          skip_autogenerated: true
          max_line_length: 120
          oelint_release: scarthgap
        
        exclude:
          - "build/*"
          - "tmp/*"
    """

    def __init__(self):
        """Initialize with default configuration."""
        self.rules: Dict[str, RuleConfig] = {}
        self.enabled_rules: Optional[Set[str]] = None  # None = use defaults
        self.disabled_rules: Set[str] = set()
        self.enabled_groups: List[str] = []
        self.disabled_groups: List[str] = []
        
        # General settings
        self.skip_autogenerated: bool = True
        self.max_line_length: int = 120
        # Yocto release oelint-adv should validate against (its release-gated
        # rules, e.g. oelint.vars.unpackdir, default to oelint-adv's own
        # newest-supported release otherwise -- see run_oelint_adv()).
        self.oelint_release: Optional[str] = None
        
        # File patterns to exclude
        self.exclude_patterns: List[str] = []
        
        # Output settings
        self.output_format: str = "text"
        self.output_file: Optional[Path] = None
        self.verbose: bool = False
        self.quiet: bool = False
        self.color: bool = True
        self.ci_mode: bool = False
        
        # Config file path (if loaded)
        self.config_file: Optional[Path] = None

    @classmethod
    def get_default_search_paths(cls) -> List[Path]:
        """
        Get the default search paths for config files.
        
        Search order:
        1. Current working directory
        2. config/ directory relative to the bake_linter package
        
        Returns:
            List of paths to search for config files
        """
        paths = [Path.cwd()]
        
        # Add the config/ directory relative to this module
        # This is: bake_linter/../config/ = tools/bake_linter/config/
        module_dir = Path(__file__).parent  # bake_linter/
        tool_root = module_dir.parent  # tools/bake_linter/
        config_dir = tool_root / "config"
        if config_dir.is_dir():
            paths.append(config_dir)
        
        return paths

    @classmethod
    def load(cls, config_path: Optional[Path] = None, 
             search_paths: Optional[List[Path]] = None) -> "LinterConfig":
        """
        Load configuration from file.
        
        Args:
            config_path: Explicit path to config file
            search_paths: Directories to search for config files
            
        Returns:
            LinterConfig instance
        """
        config = cls()
        
        # Find config file
        file_path = None
        
        if config_path:
            if config_path.exists():
                file_path = config_path
            else:
                raise FileNotFoundError(f"Config file not found: {config_path}")
        else:
            # Search for config file in default locations
            search_dirs = search_paths or cls.get_default_search_paths()
            for search_dir in search_dirs:
                for filename in CONFIG_FILENAMES:
                    candidate = search_dir / filename
                    if candidate.exists():
                        file_path = candidate
                        break
                if file_path:
                    break
        
        if file_path:
            config._load_file(file_path)
            config.config_file = file_path
        
        return config

    def _load_file(self, path: Path) -> None:
        """Load configuration from a file."""
        content = path.read_text(encoding="utf-8")
        
        if path.suffix in (".yaml", ".yml"):
            if not HAS_YAML:
                raise ImportError(
                    "PyYAML is required to load YAML config files. "
                    "Install with: pip install pyyaml"
                )
            data = yaml.safe_load(content)
        elif path.suffix == ".json":
            data = json.loads(content)
        else:
            # Try YAML first, then JSON
            try:
                if HAS_YAML:
                    data = yaml.safe_load(content)
                else:
                    data = json.loads(content)
            except Exception:
                raise ValueError(f"Cannot parse config file: {path}")
        
        if not isinstance(data, dict):
            raise ValueError(f"Config file must contain a mapping: {path}")
        
        self._apply_config(data)

    def _apply_config(self, data: Dict[str, Any]) -> None:
        """Apply configuration data from parsed file."""
        # Load rule configurations
        if "rules" in data:
            for rule_id, rule_data in data["rules"].items():
                if isinstance(rule_data, dict):
                    self.rules[rule_id] = RuleConfig.from_dict(rule_id, rule_data)
                elif isinstance(rule_data, bool):
                    self.rules[rule_id] = RuleConfig(rule_id=rule_id, enabled=rule_data)
        
        # Load settings
        if "settings" in data:
            settings = data["settings"]
            if "skip_autogenerated" in settings:
                self.skip_autogenerated = bool(settings["skip_autogenerated"])
            if "max_line_length" in settings:
                self.max_line_length = int(settings["max_line_length"])
            if "oelint_release" in settings:
                self.oelint_release = str(settings["oelint_release"])
            if "color" in settings:
                self.color = bool(settings["color"])
        
        # Load exclude patterns
        if "exclude" in data:
            self.exclude_patterns = list(data["exclude"])
        
        # Load enabled/disabled rules
        if "enable" in data:
            self.enabled_rules = set(data["enable"])
        if "disable" in data:
            self.disabled_rules = set(data["disable"])
        
        # Load groups
        if "enable_groups" in data:
            self.enabled_groups = list(data["enable_groups"])
        if "disable_groups" in data:
            self.disabled_groups = list(data["disable_groups"])

    def merge_cli_args(
        self,
        enable: Optional[List[str]] = None,
        disable: Optional[List[str]] = None,
        enable_groups: Optional[List[str]] = None,
        disable_groups: Optional[List[str]] = None,
        output_format: Optional[str] = None,
        output_file: Optional[str] = None,
        verbose: bool = False,
        quiet: bool = False,
        color: Optional[bool] = None,
        ci_mode: bool = False,
    ) -> None:
        """
        Merge CLI arguments into configuration.
        
        CLI arguments take precedence over config file settings.
        """
        # Enabled rules (CLI overrides config)
        if enable:
            if self.enabled_rules is None:
                self.enabled_rules = set()
            self.enabled_rules.update(enable)
        
        # Disabled rules (CLI adds to config)
        if disable:
            self.disabled_rules.update(disable)
        
        # Groups
        if enable_groups:
            self.enabled_groups.extend(enable_groups)
        if disable_groups:
            self.disabled_groups.extend(disable_groups)
        
        # Output settings
        if output_format:
            self.output_format = output_format
        if output_file:
            self.output_file = Path(output_file)
        
        self.verbose = verbose or self.verbose
        self.quiet = quiet or self.quiet
        
        # CI mode implies no color and specific settings
        if ci_mode:
            self.ci_mode = True
            self.color = False
        elif color is not None:
            self.color = color

    def get_rule_configs(self) -> Dict[str, RuleConfig]:
        """Get all rule configurations."""
        return dict(self.rules)

    def is_file_excluded(self, path: Path) -> bool:
        """Check if a file matches any exclude pattern."""
        import fnmatch
        
        path_str = str(path)
        for pattern in self.exclude_patterns:
            if fnmatch.fnmatch(path_str, pattern):
                return True
        return False

    def to_dict(self) -> Dict[str, Any]:
        """Convert configuration to dictionary (for debugging/logging)."""
        return {
            "rules": {k: {"enabled": v.enabled, "severity": str(v.severity) if v.severity else None}
                     for k, v in self.rules.items()},
            "enabled_rules": list(self.enabled_rules) if self.enabled_rules else None,
            "disabled_rules": list(self.disabled_rules),
            "enabled_groups": self.enabled_groups,
            "disabled_groups": self.disabled_groups,
            "settings": {
                "skip_autogenerated": self.skip_autogenerated,
                "max_line_length": self.max_line_length,
                "color": self.color,
                "ci_mode": self.ci_mode,
            },
            "exclude": self.exclude_patterns,
            "config_file": str(self.config_file) if self.config_file else None,
        }


def get_default_config() -> LinterConfig:
    """Get the default linter configuration."""
    return LinterConfig()
