"""
Regression tests for CLI, discovery, reports, and staged-file handling.

Copyright (c) 2026 OpenAI

This file is part of bake_linter. It is free software, licensed under the
GNU Lesser General Public License v3.0 or later. See COPYING.LESSER and
COPYING for details.

SPDX-License-Identifier: LGPL-3.0-or-later
"""

import json
import os
from pathlib import Path
import subprocess
import sys
from html.parser import HTMLParser

import pytest

from bake_linter.cli import main
from bake_linter.core.engine import LintEngine
from bake_linter.core.models import LintResult, LintSummary, Severity
from bake_linter.output.html import HtmlFormatter
from bake_linter.output.html_oelint import OelintHtmlFormatter


@pytest.fixture
def cli_case(tmp_path, monkeypatch):
    monkeypatch.setattr('bake_linter.cli.run_oelint_adv', lambda **kwargs: (None, None))
    recipe = tmp_path / 'example_1.0.bb'
    recipe.write_text('SUMMARY = "Example"\n')
    config = tmp_path / 'config.json'

    def run(data, *args):
        config.write_text(json.dumps(data))
        return main(['--config', str(config), str(recipe), *args])

    return recipe, run


@pytest.mark.parametrize('fmt', ['json', 'jsonl'])
def test_machine_stdout_is_parseable(cli_case, capsys, fmt):
    _, run = cli_case
    assert run({'enable': ['LICENSE001']}, '--format', fmt) == 2
    output = capsys.readouterr()
    assert 'Using config:' in output.err
    if fmt == 'json':
        assert json.loads(output.out)['bake_linter']['results']
    else:
        assert all(json.loads(line) for line in output.out.splitlines())


def test_show_config_retains_settings(cli_case, capsys):
    _, run = cli_case
    assert run({'enable': [], 'settings': {'color': False, 'oelint_release': 'scarthgap',
                                         'oelint_extra_machines': ['example-board']},
                'rules': {'STYLE002': {'options': {'max_length': 80}}}}, '--show-config') == 0
    data = json.loads(capsys.readouterr().out)
    assert data['settings']['color'] is False
    assert data['settings']['oelint_release'] == 'scarthgap'
    assert data['settings']['oelint_extra_machines'] == ['example-board']
    assert data['rules']['STYLE002']['options']['max_length'] == 80
    assert data['enabled_rules'] == []


@pytest.mark.parametrize('skip,flag,expected', [(False, [], 2), (True, [], 0),
                                               (True, ['--include-autogenerated'], 2)])
def test_autogenerated_config_reaches_engine(cli_case, skip, flag, expected):
    recipe, run = cli_case
    recipe.write_text('# Auto-generated\nSUMMARY = "Example"\n')
    assert run({'enable': ['LICENSE001'], 'settings': {'skip_autogenerated': skip}},
               '--quiet', *flag) == expected


@pytest.mark.parametrize('data,args,expected', [
    ({'disable': ['LICENSE001']}, ['--enable', 'LICENSE001'], 2),
    ({'disable_groups': ['license']}, ['--enable', 'LICENSE001'], 2),
    ({'enable': ['MANDATORY001']}, ['--enable', 'LICENSE001'], 2),
    ({'disable': ['LICENSE001']}, ['--enable-group', 'license'], 2),
    ({}, ['--enable', 'LICENSE001', '--disable', 'LICENSE001'], 0),
    ({'enable': []}, [], 0),
])
def test_cli_rule_selection_precedence(cli_case, capsys, data, args, expected):
    _, run = cli_case
    assert run(data, '--format', 'json', *args) == expected
    results = json.loads(capsys.readouterr().out)['bake_linter']['results']
    if '--enable' in args and expected == 2:
        assert {r['rule_id'] for r in results} == {'LICENSE001'}


@pytest.mark.parametrize('content', [
    'settings: [', 'rules: []', 'settings: null', 'exclude: "build/*"',
    'enable: LICENSE001', 'settings: {color: "false"}',
    'settings: {max_line_length: null}', 'settings: {oelint_extra_machines: board}',
    'rules: {LICENSE001: {severity: 3}}', 'rules: {STYLE002: {options: []}}',
])
def test_invalid_config_is_runtime_error(tmp_path, capsys, content):
    config = tmp_path / 'config.yaml'
    config.write_text(content)
    assert main(['--config', str(config), '--show-config']) == 3
    assert 'Configuration error:' in capsys.readouterr().err


def test_group_selection_in_fresh_process():
    code = '''
from bake_linter.core.engine import LintEngine
engine = LintEngine()
engine.configure(enabled_groups=['license'])
assert 'LICENSE001' in {rule.rule_id for rule in engine._get_enabled_rules()}
engine = LintEngine()
engine.configure(disabled_groups=['license'])
assert 'LICENSE001' not in {rule.rule_id for rule in engine._get_enabled_rules()}
'''
    subprocess.run([sys.executable, '-c', code], check=True)


def test_overlapping_inputs_are_scanned_once(tmp_path):
    recipe = tmp_path / 'example.bb'
    recipe.write_text('SUMMARY = "Example"\n')
    engine = LintEngine()
    engine.configure(enabled_rules=['LICENSE001'])
    assert len(engine.lint_files([tmp_path, recipe, tmp_path])) == 1
    assert engine.get_summary().files_scanned == 1


class ScriptDataParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.current = None
        self.blocks = {}

    def handle_starttag(self, tag, attrs):
        if tag == 'script':
            self.current = dict(attrs).get('id')
            if self.current:
                self.blocks[self.current] = ''

    def handle_data(self, data):
        if self.current:
            self.blocks[self.current] += data

    def handle_endtag(self, tag):
        if tag == 'script':
            self.current = None


@pytest.mark.parametrize('formatter', [HtmlFormatter, OelintHtmlFormatter])
def test_embedded_docs_cannot_close_script(monkeypatch, formatter):
    content = 'Example: </script><script>alert("example")</script>'
    if formatter is HtmlFormatter:
        monkeypatch.setattr('bake_linter.output.html.get_rule_docs_content', lambda _: content)
    else:
        from types import SimpleNamespace
        monkeypatch.setattr('bake_linter.core.oelint_integration.get_oelint_integration',
                            lambda: SimpleNamespace(get_rule_documentation=lambda _: content))
    encoded = formatter()._get_rule_docs_data({'LICENSE001': []})
    parser = ScriptDataParser()
    parser.feed('<script id="docs" type="application/json">' + encoded + '</script>')
    assert json.loads(parser.blocks['docs'])['LICENSE001'] == content


def test_chart_data_cannot_close_script():
    name = '</script><script>alert("example")</script>'
    result = LintResult('LICENSE001', Path('example.bb'), Severity.ERROR, 'Example', rule_name=name)
    summary = LintSummary.from_results([result], files_scanned=1, rules_executed=1)
    parser = ScriptDataParser()
    parser.feed(HtmlFormatter().format_results([result], summary))
    assert json.loads(parser.blocks['chart-data'])['topRuleNames'] == [name]


@pytest.mark.parametrize('filename,remove_worktree', [
    ('with spaces/example.bb', False), ('example.bb', True),
    ('with\ttab.bb', False), ('with\nnewline.bb', False), ('café.bb', False),
])
def test_hook_lints_exact_staged_content(tmp_path, filename, remove_worktree):
    repo = tmp_path / 'repo'
    repo.mkdir()
    subprocess.run(['git', 'init', '-q', str(repo)], check=True)
    recipe = repo / filename
    recipe.parent.mkdir(parents=True, exist_ok=True)
    recipe.write_text('staged content\n')
    subprocess.run(['git', '-C', str(repo), 'add', '--', filename], check=True)
    if remove_worktree:
        recipe.unlink()
    else:
        recipe.write_text('unstaged content\n')
    bin_dir = tmp_path / 'bin'
    bin_dir.mkdir()
    fake_linter = bin_dir / 'bake-linter'
    fake_linter.write_text('#!' + sys.executable + '\n' + '''
import json, os, pathlib, sys
pathlib.Path(os.environ['HOOK_CAPTURE']).write_text(json.dumps([
    [str(pathlib.Path(p)), pathlib.Path(p).read_text()] for p in sys.argv[2:]
]))
sys.exit(2)
''')
    fake_linter.chmod(0o755)
    capture = tmp_path / 'capture.json'
    hook = Path(__file__).resolve().parents[1] / 'hooks' / 'pre-commit'
    env = dict(os.environ, PATH=str(bin_dir) + os.pathsep + os.environ['PATH'],
               HOOK_CAPTURE=str(capture))
    outcome = subprocess.run(['bash', str(hook)], cwd=repo, env=env, capture_output=True, text=True)
    assert outcome.returncode == 1, outcome.stdout + outcome.stderr
    records = json.loads(capture.read_text())
    assert len(records) == 1
    assert records[0][0].endswith('/' + filename)
    assert records[0][1] == 'staged content\n'


def test_unreadable_recipe_is_runtime_error(cli_case, monkeypatch, capsys):
    recipe, run = cli_case
    original_read = Path.read_text

    def read(path, *args, **kwargs):
        if path == recipe:
            raise PermissionError('Permission denied')
        return original_read(path, *args, **kwargs)

    monkeypatch.setattr(Path, 'read_text', read)
    assert run({'enable': ['LICENSE001']}, '--quiet') == 3
    assert 'Error reading file:' in capsys.readouterr().err


def test_installed_resource_lookup(tmp_path, monkeypatch):
    from bake_linter import config
    from bake_linter.core import models

    package = tmp_path / 'site-packages' / 'bake_linter'
    docs = package / 'data' / 'rules'
    defaults = package / 'data' / 'config'
    docs.mkdir(parents=True)
    defaults.mkdir(parents=True)
    (docs / 'LICENSE001.md').write_text('# License documentation\n')
    (defaults / '.bake-linter.yaml').write_text('settings: {color: false}\n')
    monkeypatch.setattr(models, '__file__', str(package / 'core' / 'models.py'))
    monkeypatch.setattr(config, '__file__', str(package / 'config.py'))
    monkeypatch.chdir(tmp_path)
    assert models.get_rule_docs_content('LICENSE001') == '# License documentation\n'
    loaded = config.LinterConfig.load()
    assert loaded.config_file == defaults / '.bake-linter.yaml'
    assert loaded.color is False


def test_rule_crash_is_runtime_error_and_next_run_recovers(cli_case, monkeypatch, capsys):
    from bake_linter.core.registry import get_registry

    recipe, run = cli_case
    registry = get_registry()
    registry.discover_rules()
    rule = registry.get_rule('LICENSE001')
    original = rule.check

    def fail(self, context):
        raise RuntimeError('example failure')

    monkeypatch.setattr(rule, 'check', fail)
    assert run({'enable': ['LICENSE001']}, '--format', 'json') == 3
    output = capsys.readouterr()
    summary = json.loads(output.out)['bake_linter']['summary']
    assert summary['exit_code'] == 3
    assert 'example failure' in summary['runtime_errors'][0]
    assert 'example failure' in output.err
    engine = LintEngine()
    engine.configure(enabled_rules=['LICENSE001'])
    engine.lint_files([recipe])
    assert engine.get_summary().get_exit_code() == 3
    monkeypatch.setattr(rule, 'check', original)
    engine.lint_files([recipe])
    assert engine.get_summary().get_exit_code() == 2
    assert engine.get_summary().runtime_errors == []
