# -*- coding: utf-8 -*-
"""
Unit tests for configuration system.

Copyright (c) 2024-2026 Eduardo Correia <ecorreia@apliant.com.br>

This file is part of bake_linter. It is free software, licensed under the
GNU Lesser General Public License v3.0 or later. See COPYING.LESSER and
COPYING for details.

SPDX-License-Identifier: LGPL-3.0-or-later
"""

import pytest
import json
from pathlib import Path

from bake_linter.config import LinterConfig
from bake_linter.core.models import Severity


class TestConfigLoading:
    """Tests for configuration loading."""

    def test_default_config(self):
        """Test default configuration."""
        config = LinterConfig()
        
        assert config.skip_autogenerated is True
        assert config.color is True
        assert config.ci_mode is False
        assert len(config.rules) == 0

    def test_load_json_config(self, tmp_path):
        """Test loading JSON configuration."""
        config_file = tmp_path / "config.json"
        config_file.write_text(json.dumps({
            "rules": {
                "LICENSE001": {"enabled": True, "severity": "error"},
                "STYLE001": {"enabled": False},
            },
            "settings": {
                "skip_autogenerated": False,
                "max_line_length": 100,
            },
        }))
        
        config = LinterConfig.load(config_file)
        
        assert "LICENSE001" in config.rules
        assert config.rules["LICENSE001"].enabled is True
        assert config.rules["LICENSE001"].severity == Severity.ERROR
        assert config.rules["STYLE001"].enabled is False
        assert config.skip_autogenerated is False
        assert config.max_line_length == 100

    def test_load_yaml_config(self, tmp_path):
        """Test loading YAML configuration."""
        pytest.importorskip("yaml")
        
        config_file = tmp_path / "config.yaml"
        config_file.write_text("""
rules:
  LICENSE001:
    enabled: true
    severity: warning
  MANDATORY001:
    enabled: false

settings:
  color: false
  
exclude:
  - "build/*"
  - "tmp/*"
""")
        
        config = LinterConfig.load(config_file)
        
        assert "LICENSE001" in config.rules
        assert config.rules["LICENSE001"].severity == Severity.WARNING
        assert config.rules["MANDATORY001"].enabled is False
        assert config.color is False
        assert "build/*" in config.exclude_patterns

    def test_config_file_not_found(self, tmp_path):
        """Test error when config file not found."""
        with pytest.raises(FileNotFoundError):
            LinterConfig.load(tmp_path / "nonexistent.yaml")


class TestCLIOverride:
    """Tests for CLI override behavior."""

    def test_cli_enable_overrides_config(self, tmp_path):
        """Test that CLI enable overrides config."""
        config_file = tmp_path / "config.json"
        config_file.write_text(json.dumps({
            "disable": ["LICENSE001"],
        }))
        
        config = LinterConfig.load(config_file)
        config.merge_cli_args(enable=["LICENSE001"])
        
        # CLI enable should win
        assert "LICENSE001" in config.enabled_rules

    def test_cli_disable_adds_to_config(self, tmp_path):
        """Test that CLI disable adds to config."""
        config_file = tmp_path / "config.json"
        config_file.write_text(json.dumps({
            "disable": ["STYLE001"],
        }))
        
        config = LinterConfig.load(config_file)
        config.merge_cli_args(disable=["STYLE002"])
        
        # Both should be disabled
        assert "STYLE001" in config.disabled_rules
        assert "STYLE002" in config.disabled_rules

    def test_ci_mode_disables_color(self):
        """Test that CI mode disables color."""
        config = LinterConfig()
        assert config.color is True
        
        config.merge_cli_args(ci_mode=True)
        
        assert config.ci_mode is True
        assert config.color is False


class TestFileExclusion:
    """Tests for file exclusion patterns."""

    def test_exclude_pattern_matching(self):
        """Test exclude pattern matching."""
        config = LinterConfig()
        config.exclude_patterns = ["build/*", "*.bak"]
        
        assert config.is_file_excluded(Path("build/recipe.bb"))
        assert config.is_file_excluded(Path("recipe.bb.bak"))
        assert not config.is_file_excluded(Path("recipes/recipe.bb"))


class TestMaxLineLength:
    """settings.max_line_length reaches STYLE002."""

    def test_setting_is_the_style002_limit(self, tmp_path):
        config_file = tmp_path / ".bake-linter.yaml"
        config_file.write_text("settings:\n  max_line_length: 80\n")
        config = LinterConfig.load(config_file)
        assert config.rules["STYLE002"].options["max_length"] == 80

    def test_rule_option_wins(self, tmp_path):
        config_file = tmp_path / ".bake-linter.yaml"
        config_file.write_text(
            "rules:\n  STYLE002:\n    options:\n      max_length: 100\n"
            "settings:\n  max_line_length: 80\n"
        )
        config = LinterConfig.load(config_file)
        assert config.rules["STYLE002"].options["max_length"] == 100
