#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Documentation generator for bake-linter rules.

This script generates markdown documentation for all rules based on their
class definitions and a template.

Usage:
    python -m bake_linter.utils.gen_docs [--force]

Copyright (c) 2024-2026 Eduardo Correia <ecorreia@apliant.com.br>

This file is part of bake_linter. It is free software, licensed under the
GNU Lesser General Public License v3.0 or later. See COPYING.LESSER and
COPYING for details.

SPDX-License-Identifier: LGPL-3.0-or-later
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Optional

from bake_linter.core.registry import get_registry


def get_template() -> str:
    """Load the documentation template."""
    template_path = Path(__file__).parent.parent.parent / "docs" / "rules" / "template.md"
    
    if not template_path.exists():
        print(f"Error: Template not found at {template_path}", file=sys.stderr)
        sys.exit(1)
    
    return template_path.read_text()


def generate_doc_for_rule(rule_cls, template: str, force: bool = False) -> Optional[Path]:
    """
    Generate documentation for a single rule.
    
    Args:
        rule_cls: The rule class
        template: The template string
        force: Whether to overwrite existing documentation
        
    Returns:
        Path to the generated file, or None if skipped
    """
    docs_dir = Path(__file__).parent.parent.parent / "docs" / "rules"
    output_file = docs_dir / f"{rule_cls.rule_id}.md"
    
    # Skip if exists and not forcing
    if output_file.exists() and not force:
        print(f"Skipping {rule_cls.rule_id} (already exists, use --force to overwrite)")
        return None
    
    # Extract rule information
    rule_id = rule_cls.rule_id
    name = rule_cls.name
    description = rule_cls.description
    severity = str(rule_cls.default_severity)
    enabled = "Yes" if rule_cls.enabled_by_default else "No"
    
    # Determine category from groups
    category = rule_cls.groups[0] if rule_cls.groups else "general"
    
    # Basic placeholders - in a full implementation, you'd extract these from
    # docstrings or additional metadata
    content = template
    content = content.replace("{RULE_ID}", rule_id)
    content = content.replace("{RULE_NAME}", name)
    content = content.replace("{SEVERITY}", severity)
    content = content.replace("{CATEGORY}", category)
    content = content.replace("{ENABLED}", enabled)
    content = content.replace("{DESCRIPTION}", description)
    
    # Placeholders that need manual filling
    content = content.replace("{BAD_EXAMPLE}", "# TODO: Add example of code that violates this rule")
    content = content.replace("{WHY_BAD}", "TODO: Explain why this pattern is problematic")
    content = content.replace("{GOOD_EXAMPLE}", "# TODO: Add example of correct code")
    content = content.replace("{FIX_EXPLANATION}", "TODO: Explain how to fix the issue")
    content = content.replace("{OPTIONS_EXAMPLE}", "# options:\n    #   key: value  # TODO: Add rule-specific options if any")
    
    # Write the file
    output_file.write_text(content)
    print(f"Generated documentation for {rule_id} -> {output_file}")
    
    return output_file


RULES_DIR = Path(__file__).parent.parent.parent / "docs" / "rules"
INDEX_PATH = RULES_DIR / "README.md"
INDEX_BEGIN = "<!-- rule-index:begin (generated by gen_docs --index) -->"
INDEX_END = "<!-- rule-index:end -->"


def build_rule_index(rules) -> str:
    """Markdown tables of all rules, one per rule family (ID prefix)."""
    families = {}
    for rule_id, rule_cls in sorted(rules.items()):
        # Only the rules shipped in the package, not ones defined elsewhere
        # (rule classes register themselves, tests define some too)
        if not rule_cls.__module__.startswith("bake_linter.rules."):
            continue
        family = re.match(r"[A-Z]+", rule_id).group(0)
        families.setdefault(family, []).append((rule_id, rule_cls))

    parts = []
    for family, members in families.items():
        parts.append(f"### {family}\n")
        parts.append("| Rule | Name | Severity | Enabled | Description |")
        parts.append("| --- | --- | --- | --- | --- |")
        for rule_id, rule_cls in members:
            enabled = "yes" if getattr(rule_cls, "enabled_by_default", True) else "no"
            description = rule_cls.description.replace("|", "\\|")
            parts.append(
                f"| [{rule_id}]({rule_id}.md) | {rule_cls.name} | "
                f"{rule_cls.default_severity.name.lower()} | {enabled} | {description} |"
            )
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def render_index(text: str, rules) -> str:
    """*text* with the generated section between the index markers replaced."""
    begin, end = text.index(INDEX_BEGIN), text.index(INDEX_END)
    return (
        text[:begin + len(INDEX_BEGIN)] + "\n\n" + build_rule_index(rules)
        + "\n" + text[end:]
    )


def main():
    """Main entry point for documentation generator."""
    parser = argparse.ArgumentParser(
        description="Generate documentation for bake-linter rules"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing documentation files"
    )
    parser.add_argument(
        "--rule",
        metavar="RULE_ID",
        help="Generate documentation for a specific rule only"
    )
    parser.add_argument(
        "--index",
        action="store_true",
        help=f"Only regenerate the rule index in {INDEX_PATH.relative_to(INDEX_PATH.parents[2])}"
    )
    
    args = parser.parse_args()

    if args.index:
        registry = get_registry()
        registry.discover_rules()
        rules = registry.get_all_rules()
        INDEX_PATH.write_text(render_index(INDEX_PATH.read_text(), rules))
        print(f"Wrote the index of {len(rules)} rules to {INDEX_PATH}")
        return
    
    # Load template
    template = get_template()
    
    # Discover all rules
    registry = get_registry()
    registry.discover_rules()
    
    # Get rules to document
    if args.rule:
        rules = {args.rule: registry.get_all_rules().get(args.rule)}
        if rules[args.rule] is None:
            print(f"Error: Rule {args.rule} not found", file=sys.stderr)
            sys.exit(1)
    else:
        rules = registry.get_all_rules()
    
    # Generate documentation
    generated = []
    skipped = []
    
    for rule_id, rule_cls in sorted(rules.items()):
        result = generate_doc_for_rule(rule_cls, template, args.force)
        if result:
            generated.append(rule_id)
        else:
            skipped.append(rule_id)
    
    # Summary
    print("\n" + "=" * 70)
    print(f"Documentation generation complete!")
    print(f"  Generated: {len(generated)} files")
    print(f"  Skipped: {len(skipped)} files")
    
    if generated:
        print(f"\nGenerated files need manual editing to fill in:")
        print("  - Bad code examples")
        print("  - Why it's bad explanations")
        print("  - Good code examples")
        print("  - Fix explanations")
        print("  - Configuration options (if applicable)")
    
    print("\nNext steps:")
    print("  1. Review generated files in docs/rules/")
    print("  2. Fill in TODO placeholders with actual examples")
    print("  3. Test the documentation with real users")
    print("=" * 70)


if __name__ == "__main__":
    main()
