"""
HTML output formatter for oelint-adv reports.

Generates a standalone HTML report for oelint-adv results with:
- Summary dashboard
- Per-file issue breakdown
- Per-rule grouping
- Color-coded severities
- Expandable sections
- Rule documentation viewer

This is Option B implementation - a separate file alongside the main report.

Copyright (c) 2024-2026 Eduardo Correia <ecorreia@apliant.com.br>

This file is part of bake_linter. It is free software, licensed under the
GNU Lesser General Public License v3.0 or later. See COPYING.LESSER and
COPYING for details.

SPDX-License-Identifier: LGPL-3.0-or-later
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional, TextIO, TYPE_CHECKING
from collections import defaultdict
import html
import json

if TYPE_CHECKING:
    from bake_linter.core.oelint_integration import OelintResult, OelintSummary


class OelintHtmlFormatter:
    """
    HTML formatter for oelint-adv reports.
    
    Generates a self-contained HTML file with embedded CSS and JavaScript
    for an interactive oelint-adv report.
    """

    def __init__(
        self,
        output: Optional[TextIO] = None,
        verbose: bool = False,
        title: str = "oelint-adv Report by Bake Linter",
    ):
        self.output = output
        self.verbose = verbose
        self.title = title

    def format_results(
        self,
        results: List["OelintResult"],
        summary: "OelintSummary",
    ) -> str:
        """Generate HTML report for oelint-adv results."""
        # Group results by file
        by_file: Dict[Path, List["OelintResult"]] = defaultdict(list)
        for result in results:
            by_file[result.file].append(result)
        
        # Group results by rule
        by_rule: Dict[str, List["OelintResult"]] = defaultdict(list)
        for result in results:
            by_rule[result.rule_id].append(result)
        
        # Group rules by category (rule_group)
        rule_categories: Dict[str, str] = {}
        for result in results:
            rule_categories[result.rule_id] = result.rule_group.upper()
        
        return self._render_html(results, summary, by_file, by_rule, rule_categories)

    def write(
        self,
        results: List["OelintResult"],
        summary: "OelintSummary",
    ) -> None:
        """Format and write results to output."""
        formatted = self.format_results(results, summary)
        if self.output:
            self.output.write(formatted)
            if not formatted.endswith("\n"):
                self.output.write("\n")

    def _render_html(
        self,
        results: List["OelintResult"],
        summary: "OelintSummary",
        by_file: Dict[Path, List["OelintResult"]],
        by_rule: Dict[str, List["OelintResult"]],
        rule_categories: Dict[str, str],
    ) -> str:
        """Render the complete HTML document."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        version_info = f"Version: {summary.tool_version}" if summary.tool_version else ""
        
        return f"""<!DOCTYPE html>
<!--
    oelint-adv Report (generated by Bake Linter)
    (c) 2024-2026 Eduardo Correia <ecorreia@apliant.com.br>
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(self.title)}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
    {self._get_styles()}
</head>
<body>
    <div class="container">
        <header>
            <h1>🔍 {html.escape(self.title)}</h1>
            <p class="timestamp">Generated: {timestamp}</p>
            <p class="version-info">{version_info}</p>
            <div class="copyright-section">
                <!-- START: DO NOT REMOVE OR MODIFY THIS COPYRIGHT NOTICE -->
                <p class="copyright-main">© 2024-2026 <a href="https://www.apliant.com.br/eduardo" target="_blank" class="author-link">Eduardo Correia</a> — <a href="https://www.apliant.com.br/eduardo" target="_blank" class="cv-link">📄 Curriculum Vitae</a></p>
                <p class="copyright-links">
                    <a href="mailto:ecorreia@apliant.com.br" class="contact-link">📧 ecorreia@apliant.com.br</a>
                    <span class="link-separator">•</span>
                    <a href="https://www.apliant.com.br" target="_blank" class="contact-link">🌐 www.apliant.com.br</a>
                    <span class="link-separator">•</span>
                    <a href="https://www.linkedin.com/in/c99-eduardo/" target="_blank" class="contact-link linkedin-link">💼 LinkedIn</a>
                </p>
                <!-- <p class="tool-info">Results from <a href="https://github.com/priv-kweihmann/oelint-adv" target="_blank">oelint-adv</a> - Advanced OELint for Yocto/OpenEmbedded</p> -->
                <!-- END: DO NOT REMOVE OR MODIFY THIS COPYRIGHT NOTICE -->
            </div>
        </header>
        
        {self._render_summary(summary)}
        
        <nav class="tabs">
            <button class="tab-btn" data-tab="files">📁 By File</button>
            <button class="tab-btn active" data-tab="rules">📋 By Rule</button>
            <button class="tab-btn" data-tab="statistics">📊 Statistics</button>
        </nav>
        
        <div class="severity-filters">
            <span class="filter-label">Filter by Severity:</span>
            <button class="filter-btn active" data-severity="error">🔴 Errors</button>
            <button class="filter-btn active" data-severity="warning">🟡 Warnings</button>
            <button class="filter-btn active" data-severity="info">🔵 Info</button>
        </div>
        
        <div id="files" class="tab-content">
            <div class="expand-controls">
                <button class="expand-btn" data-action="expand-all" data-target="files">▼ Expand All</button>
                <button class="expand-btn" data-action="collapse-all" data-target="files">▲ Collapse All</button>
            </div>
            {self._render_files_section(by_file)}
        </div>
        
        <div id="rules" class="tab-content active">
            <div class="expand-controls">
                <button class="expand-btn" data-action="expand-all" data-target="rules">▼▼ Items</button>
                <button class="expand-btn" data-action="expand-level1" data-target="rules">▲ Files</button>
                <button class="expand-btn" data-action="collapse-level1" data-target="rules">▲▲ Rules</button>
                <button class="expand-btn" data-action="collapse-all" data-target="rules">▲▲▲ Categories</button>
            </div>
            {self._render_rules_section(by_rule, rule_categories)}
        </div>
        
        <div id="statistics" class="tab-content">
            {self._render_statistics_section(summary, by_rule, by_file, rule_categories)}
        </div>
        
        <footer>
            <p>oelint-adv Report • {summary.total_issues} issue(s) in {summary.files_scanned} file(s)</p>
        </footer>
    </div>
    
    <!-- Rule Documentation Modal -->
    <div id="rule-docs-modal" class="rule-docs-modal">
        <div class="rule-docs-modal-content">
            <div class="rule-docs-modal-header">
                <h2 id="rule-docs-title">Rule Documentation</h2>
                <button class="rule-docs-close" onclick="closeRuleDocsModal()">&times;</button>
            </div>
            <div id="rule-docs-body" class="rule-docs-modal-body">
                <p>Loading documentation...</p>
            </div>
        </div>
    </div>
    
    <!-- Rule Documentation Data -->
    <script id="rule-docs-data" type="application/json">{self._get_rule_docs_data(by_rule)}</script>
    
    {self._get_scripts()}
</body>
</html>"""

    def _render_summary(self, summary: "OelintSummary") -> str:
        """Render the summary dashboard."""
        status_class = "success" if summary.total_issues == 0 else (
            "error" if summary.errors > 0 else "warning"
        )
        status_text = "All Clear!" if summary.total_issues == 0 else (
            f"{summary.total_issues} Issue(s) Found"
        )
        
        return f"""
        <section class="summary {status_class}">
            <div class="summary-header">
                <span class="status-badge {status_class}">{status_text}</span>
            </div>
            <div class="summary-stats">
                <div class="stat error">
                    <span class="stat-value">{summary.errors}</span>
                    <span class="stat-label">Errors</span>
                </div>
                <div class="stat warning">
                    <span class="stat-value">{summary.warnings}</span>
                    <span class="stat-label">Warnings</span>
                </div>
                <div class="stat info">
                    <span class="stat-value">{summary.infos}</span>
                    <span class="stat-label">Info</span>
                </div>
                <div class="stat neutral">
                    <span class="stat-value">{summary.files_scanned}</span>
                    <span class="stat-label">Files Scanned</span>
                </div>
                <div class="stat neutral">
                    <span class="stat-value">{len(summary.rules_triggered)}</span>
                    <span class="stat-label">Rules Triggered</span>
                </div>
            </div>
        </section>"""

    def _render_files_section(self, by_file: Dict[Path, List["OelintResult"]]) -> str:
        """Render the files section."""
        if not by_file:
            return '<p class="no-issues">✓ No issues found in any files!</p>'
        
        sections = []
        for file_path in sorted(by_file.keys()):
            file_results = sorted(by_file[file_path], key=lambda r: r.line)
            
            error_count = sum(1 for r in file_results if r.severity == 'error')
            warning_count = sum(1 for r in file_results if r.severity == 'warning')
            info_count = sum(1 for r in file_results if r.severity == 'info')
            
            badges = []
            if error_count:
                badges.append(f'<span class="badge error">{error_count} E</span>')
            if warning_count:
                badges.append(f'<span class="badge warning">{warning_count} W</span>')
            if info_count:
                badges.append(f'<span class="badge info">{info_count} I</span>')
            
            issues_html = "\n".join(self._render_result(r) for r in file_results)
            
            sections.append(f"""
            <details class="file-section" open>
                <summary>
                    <span class="file-path">{html.escape(str(file_path))}</span>
                    <span class="file-badges">{' '.join(badges)}</span>
                </summary>
                <div class="file-issues">
                    {issues_html}
                </div>
            </details>""")
        
        return "\n".join(sections)

    def _render_rules_section(
        self,
        by_rule: Dict[str, List["OelintResult"]],
        rule_categories: Dict[str, str],
    ) -> str:
        """Render the rules section with category grouping."""
        if not by_rule:
            return '<p class="no-issues">✓ No issues found!</p>'
        
        # Group rules by category
        by_category: Dict[str, Dict[str, List["OelintResult"]]] = defaultdict(dict)
        for rule_id, rule_results in by_rule.items():
            category = rule_categories.get(rule_id, 'OTHER')
            by_category[category][rule_id] = rule_results
        
        category_sections = []
        for category in sorted(by_category.keys()):
            rules_in_category = by_category[category]
            
            # Calculate category totals
            cat_errors = sum(sum(1 for r in results if r.severity == 'error') for results in rules_in_category.values())
            cat_warnings = sum(sum(1 for r in results if r.severity == 'warning') for results in rules_in_category.values())
            cat_infos = sum(sum(1 for r in results if r.severity == 'info') for results in rules_in_category.values())
            cat_total = cat_errors + cat_warnings + cat_infos
            
            cat_badges = []
            if cat_errors:
                cat_badges.append(f'<span class="badge error">{cat_errors} E</span>')
            if cat_warnings:
                cat_badges.append(f'<span class="badge warning">{cat_warnings} W</span>')
            if cat_infos:
                cat_badges.append(f'<span class="badge info">{cat_infos} I</span>')
            
            rule_sections = []
            for rule_id in sorted(rules_in_category.keys()):
                rule_results = rules_in_category[rule_id]
                
                error_count = sum(1 for r in rule_results if r.severity == 'error')
                warning_count = sum(1 for r in rule_results if r.severity == 'warning')
                info_count = sum(1 for r in rule_results if r.severity == 'info')
                
                badges = []
                if error_count:
                    badges.append(f'<span class="badge error">{error_count}</span>')
                if warning_count:
                    badges.append(f'<span class="badge warning">{warning_count}</span>')
                if info_count:
                    badges.append(f'<span class="badge info">{info_count}</span>')
                
                # Group by file within rule
                results_by_file: Dict[Path, List["OelintResult"]] = defaultdict(list)
                for r in rule_results:
                    results_by_file[r.file].append(r)
                
                file_sections = []
                for file_path in sorted(results_by_file.keys()):
                    file_results = sorted(results_by_file[file_path], key=lambda r: r.line)
                    issues_html = "\n".join(self._render_result(r) for r in file_results)
                    
                    file_error_count = sum(1 for r in file_results if r.severity == 'error')
                    file_warning_count = sum(1 for r in file_results if r.severity == 'warning')
                    file_info_count = sum(1 for r in file_results if r.severity == 'info')
                    
                    file_badges = []
                    if file_error_count:
                        file_badges.append(f'<span class="badge error">{file_error_count} E</span>')
                    if file_warning_count:
                        file_badges.append(f'<span class="badge warning">{file_warning_count} W</span>')
                    if file_info_count:
                        file_badges.append(f'<span class="badge info">{file_info_count} I</span>')
                    
                    file_sections.append(f"""
                    <details class="rule-file-section" open>
                        <summary>
                            <span class="file-path">📄 {html.escape(str(file_path))}</span>
                            <span class="file-badges">{' '.join(file_badges)}</span>
                        </summary>
                        <div class="rule-file-issues">
                            {issues_html}
                        </div>
                    </details>""")
                
                files_html = "\n".join(file_sections)
                
                # Help link for rule documentation
                help_link = f'<a href="#" class="rule-help-link" data-rule-id="{html.escape(rule_id)}" title="View rule documentation">❓</a>'
                
                rule_sections.append(f"""
                <details class="rule-section" open>
                    <summary>
                        <span class="rule-id">{html.escape(rule_id)}</span>
                        {help_link}
                        <span class="rule-count">{' '.join(badges)} ({len(rule_results)} occurrence(s))</span>
                    </summary>
                    <div class="rule-issues">
                        {files_html}
                    </div>
                </details>""")
            
            rules_html = "\n".join(rule_sections)
            
            category_sections.append(f"""
            <details class="category-section" open>
                <summary>
                    <span class="category-name">📁 {html.escape(category)}</span>
                    <span class="category-badges">{' '.join(cat_badges)}</span>
                    <span class="category-count">({cat_total} issue(s) in {len(rules_in_category)} rule(s))</span>
                </summary>
                <div class="category-rules">
                    {rules_html}
                </div>
            </details>""")
        
        return "\n".join(category_sections)

    def _render_result(self, result: "OelintResult") -> str:
        """Render a single result."""
        severity_class = result.severity
        
        line_info = f'<span class="line-num">Line {result.line}</span>' if result.line else ""
        
        return f"""
        <div class="issue {severity_class}" data-severity="{severity_class}">
            <div class="issue-header">
                {line_info}
                <span class="severity-badge {severity_class}">{result.severity.upper()}</span>
                <span class="rule-id-small">{html.escape(result.rule_id)}</span>
            </div>
            <div class="issue-message">{html.escape(result.message)}</div>
        </div>"""

    def _render_statistics_section(
        self,
        summary: "OelintSummary",
        by_rule: Dict[str, List["OelintResult"]],
        by_file: Dict[Path, List["OelintResult"]],
        rule_categories: Dict[str, str],
    ) -> str:
        """Render the statistics section with charts."""
        # Prepare data for charts - matching the original html.py format
        severity_data = {
            'labels': ['Errors', 'Warnings', 'Info'],
            'values': [summary.errors, summary.warnings, summary.infos],
            'colors': ['#dc3545', '#ffc107', '#17a2b8'],
        }
        
        # Category data with severity breakdown
        category_counts: Dict[str, Dict[str, int]] = defaultdict(lambda: {'errors': 0, 'warnings': 0, 'infos': 0})
        for rule_id, rule_results in by_rule.items():
            category = rule_categories.get(rule_id, 'OTHER')
            for r in rule_results:
                if r.severity == 'error':
                    category_counts[category]['errors'] += 1
                elif r.severity == 'warning':
                    category_counts[category]['warnings'] += 1
                else:
                    category_counts[category]['infos'] += 1
        
        # Top rules by issue count with severity breakdown
        rule_stats = []
        for rule_id, results in by_rule.items():
            errors = sum(1 for r in results if r.severity == 'error')
            warnings = sum(1 for r in results if r.severity == 'warning')
            infos = sum(1 for r in results if r.severity == 'info')
            total = errors + warnings + infos
            rule_stats.append((rule_id, total, errors, warnings, infos))
        top_rules = sorted(rule_stats, key=lambda x: -x[1])[:15]
        
        # File issues distribution with severity breakdown
        file_stats = []
        for f, results in by_file.items():
            errors = sum(1 for r in results if r.severity == 'error')
            warnings = sum(1 for r in results if r.severity == 'warning')
            infos = sum(1 for r in results if r.severity == 'info')
            total = errors + warnings + infos
            file_stats.append((str(f.name), total, errors, warnings, infos))
        top_files = sorted(file_stats, key=lambda x: -x[1])[:10]
        
        # Encode data for JavaScript
        severity_json = json.dumps(severity_data)
        category_labels = json.dumps(list(category_counts.keys()))
        category_errors = json.dumps([v['errors'] for v in category_counts.values()])
        category_warnings = json.dumps([v['warnings'] for v in category_counts.values()])
        category_infos = json.dumps([v['infos'] for v in category_counts.values()])
        
        top_rule_labels = json.dumps([r[0] for r in top_rules])
        top_rule_values = json.dumps([r[1] for r in top_rules])
        top_rule_errors = json.dumps([r[2] for r in top_rules])
        top_rule_warnings = json.dumps([r[3] for r in top_rules])
        top_rule_infos = json.dumps([r[4] for r in top_rules])
        
        top_file_labels = json.dumps([f[0] for f in top_files])
        top_file_values = json.dumps([f[1] for f in top_files])
        top_file_errors = json.dumps([f[2] for f in top_files])
        top_file_warnings = json.dumps([f[3] for f in top_files])
        top_file_infos = json.dumps([f[4] for f in top_files])
        
        return f"""
        <div class="statistics-container">
            <h2>📊 oelint-adv Analysis Dashboard</h2>
            
            <div class="stats-grid">
                <div class="chart-card">
                    <h3>🎯 Severity Distribution</h3>
                    <div class="chart-wrapper">
                        <canvas id="severityPieChart"></canvas>
                    </div>
                    <p class="chart-description">Distribution of issues by severity level</p>
                </div>
                
                <div class="chart-card">
                    <h3>📊 Severity Breakdown</h3>
                    <div class="chart-wrapper">
                        <canvas id="severityDoughnutChart"></canvas>
                    </div>
                    <p class="chart-description">Proportional view of issue types</p>
                </div>
                
                <div class="chart-card wide">
                    <h3>📁 Issues by Category</h3>
                    <div class="chart-wrapper-wide">
                        <canvas id="categoryBarChart"></canvas>
                    </div>
                    <p class="chart-description">Stacked bar chart showing errors, warnings, and info by rule category</p>
                </div>
                
                <div class="chart-card wide">
                    <h3>🔝 Top 15 Rules by Issue Count</h3>
                    <div class="chart-wrapper-wide">
                        <canvas id="topRulesChart"></canvas>
                    </div>
                    <p class="chart-description">Rules that generated the most issues</p>
                </div>
                
                <div class="chart-card wide">
                    <h3>📄 Top 10 Files by Issue Count</h3>
                    <div class="chart-wrapper-wide">
                        <canvas id="topFilesChart"></canvas>
                    </div>
                    <p class="chart-description">Files with the highest number of issues</p>
                </div>
                
                <div class="chart-card">
                    <h3>📈 Quick Stats</h3>
                    <div class="quick-stats">
                        <div class="quick-stat">
                            <span class="qs-value" id="qs-total-issues">{summary.total_issues}</span>
                            <span class="qs-label">Total Issues</span>
                        </div>
                        <div class="quick-stat">
                            <span class="qs-value" id="qs-files-with-issues">{len(by_file)}</span>
                            <span class="qs-label">Files with Issues</span>
                        </div>
                        <div class="quick-stat">
                            <span class="qs-value" id="qs-rules-triggered">{len(by_rule)}</span>
                            <span class="qs-label">Rules Triggered</span>
                        </div>
                        <div class="quick-stat">
                            <span class="qs-value" id="qs-categories-affected">{len(category_counts)}</span>
                            <span class="qs-label">Categories Affected</span>
                        </div>
                        <div class="quick-stat">
                            <span class="qs-value" id="qs-avg-issues-file">{summary.total_issues / max(len(by_file), 1):.1f}</span>
                            <span class="qs-label">Avg Issues/File</span>
                        </div>
                        <div class="quick-stat error-highlight">
                            <span class="qs-value" id="qs-error-rate">{(summary.errors / max(summary.total_issues, 1) * 100):.1f}%</span>
                            <span class="qs-label">Error Rate</span>
                        </div>
                    </div>
                </div>
                
                <div class="chart-card">
                    <h3>🏆 Health Score</h3>
                    <div class="health-score-container">
                        <canvas id="healthGauge"></canvas>
                        <div class="health-score-text">
                            <span class="health-value" id="healthValue">--</span>
                            <span class="health-label">Code Health</span>
                        </div>
                    </div>
                    <p class="chart-description">Based on error/warning ratio and issue density</p>
                </div>
            </div>
        </div>
        
        <script id="chart-data" type="application/json">
        {{
            "severity": {severity_json},
            "categoryLabels": {category_labels},
            "categoryErrors": {category_errors},
            "categoryWarnings": {category_warnings},
            "categoryInfos": {category_infos},
            "topRuleLabels": {top_rule_labels},
            "topRuleValues": {top_rule_values},
            "topRuleErrors": {top_rule_errors},
            "topRuleWarnings": {top_rule_warnings},
            "topRuleInfos": {top_rule_infos},
            "topFileLabels": {top_file_labels},
            "topFileValues": {top_file_values},
            "topFileErrors": {top_file_errors},
            "topFileWarnings": {top_file_warnings},
            "topFileInfos": {top_file_infos},
            "totalIssues": {summary.total_issues},
            "errors": {summary.errors},
            "warnings": {summary.warnings},
            "infos": {summary.infos},
            "filesScanned": {summary.files_scanned}
        }}
        </script>"""

    def _get_rule_docs_data(self, by_rule: Dict[str, List["OelintResult"]]) -> str:
        """Get rule documentation data as JSON for embedding."""
        from bake_linter.core.oelint_integration import get_oelint_integration
        
        integration = get_oelint_integration()
        docs = {}
        
        for rule_id in by_rule.keys():
            doc_content = integration.get_rule_documentation(rule_id)
            if doc_content:
                docs[rule_id] = doc_content
            else:
                # Provide a default message
                docs[rule_id] = f"# {rule_id}\n\nNo documentation available for this rule.\n\nPlease refer to the oelint-adv documentation at: https://github.com/priv-kweihmann/oelint-adv"
        
        return json.dumps(docs)

    def _get_styles(self) -> str:
        """Get embedded CSS styles."""
        return """<style>
:root {
    --color-error: #dc3545;
    --color-error-bg: #f8d7da;
    --color-warning: #ffc107;
    --color-warning-bg: #fff3cd;
    --color-info: #17a2b8;
    --color-info-bg: #d1ecf1;
    --color-success: #28a745;
    --color-success-bg: #d4edda;
    --color-neutral: #6c757d;
    --color-neutral-bg: #e9ecef;
    --color-purple: #8b5cf6;
}

* { box-sizing: border-box; }

/* Form controls do not inherit the page font by default */
button, input, select, textarea {
    font-family: inherit;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
    line-height: 1.6;
    color: #333;
    background: #f5f5f5;
    margin: 0;
    padding: 20px;
}

.container {
    max-width: 1400px;
    margin: 0 auto;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    overflow: hidden;
}

header {
    background: linear-gradient(135deg, #8b5cf6 0%, #a855f7 100%);
    color: white;
    padding: 30px;
    text-align: center;
}

header h1 {
    margin: 0 0 10px 0;
    font-size: 2em;
}

.timestamp, .version-info {
    opacity: 0.9;
    font-size: 0.9em;
    margin: 5px 0;
}

/* Author/Copyright Section - Fancy animated gradient box */
.copyright-section {
    margin-top: 20px;
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
    border-radius: 16px;
    padding: 2rem;
    text-align: center;
    position: relative;
    overflow: hidden;
    box-shadow: 
        0 8px 32px rgba(139, 92, 246, 0.4),
        0 0 0 1px rgba(139, 92, 246, 0.3),
        inset 0 1px 0 rgba(255, 255, 255, 0.1);
    border: 3px solid;
    border-image: linear-gradient(135deg, #8b5cf6, #06b6d4, #8b5cf6) 1;
    animation: borderGlow 3s ease-in-out infinite;
}

.copyright-section::before {
    content: '';
    position: absolute;
    top: -50%;
    left: -50%;
    width: 200%;
    height: 200%;
    background: radial-gradient(circle, rgba(139, 92, 246, 0.1) 0%, transparent 70%);
    animation: rotate 10s linear infinite;
    pointer-events: none;
}

.copyright-section > * {
    position: relative;
    z-index: 1;
}

@keyframes borderGlow {
    0%, 100% { 
        box-shadow: 
            0 8px 32px rgba(139, 92, 246, 0.4),
            0 0 0 1px rgba(139, 92, 246, 0.3),
            inset 0 1px 0 rgba(255, 255, 255, 0.1);
    }
    50% { 
        box-shadow: 
            0 8px 48px rgba(139, 92, 246, 0.6),
            0 0 0 1px rgba(139, 92, 246, 0.5),
            inset 0 1px 0 rgba(255, 255, 255, 0.15);
    }
}

@keyframes rotate {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
}

.copyright-main {
    font-size: 1.1em;
    margin: 0 0 12px 0;
    color: #f1f5f9;
}

.copyright-main a {
    color: #a855f7;
    text-decoration: none;
    font-weight: 600;
    transition: color 0.2s, text-shadow 0.2s;
}

.copyright-main a:hover {
    color: #c084fc;
    text-shadow: 0 0 8px rgba(168, 85, 247, 0.5);
}

.author-link {
    font-weight: 700 !important;
}

.cv-link {
    margin-left: 8px;
    font-size: 0.95em;
}

.copyright-links {
    font-size: 0.9em;
    margin: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
    gap: 12px;
    color: #94a3b8;
}

.contact-link {
    color: #94a3b8;
    text-decoration: none;
    padding: 6px 12px;
    border-radius: 8px;
    transition: all 0.3s ease;
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
}

.contact-link:hover {
    color: #f1f5f9;
    background: rgba(139, 92, 246, 0.2);
    border-color: rgba(139, 92, 246, 0.4);
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(139, 92, 246, 0.3);
}

.linkedin-link:hover {
    background: rgba(10, 102, 194, 0.3);
    border-color: rgba(10, 102, 194, 0.5);
    box-shadow: 0 4px 12px rgba(10, 102, 194, 0.3);
}

.link-separator {
    color: #475569;
}

.tool-info {
    margin-top: 10px;
    font-size: 0.85em;
    opacity: 0.9;
}

.tool-info a {
    color: white;
    text-decoration: none;
}

.tool-info a:hover {
    text-decoration: underline;
}

/* Summary Section */
.summary {
    padding: 20px 30px;
    border-bottom: 1px solid #eee;
}

.summary.success { background: var(--color-success-bg); }
.summary.error { background: var(--color-error-bg); }
.summary.warning { background: var(--color-warning-bg); }

.summary-header {
    text-align: center;
    margin-bottom: 20px;
}

.status-badge {
    display: inline-block;
    padding: 8px 20px;
    border-radius: 20px;
    font-weight: bold;
    color: white;
}

.status-badge.success { background: var(--color-success); }
.status-badge.error { background: var(--color-error); }
.status-badge.warning { background: #e0a800; color: #333; }

.summary-stats {
    display: flex;
    justify-content: center;
    gap: 30px;
    flex-wrap: wrap;
}

.stat {
    text-align: center;
    padding: 15px 25px;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}

.stat-value {
    display: block;
    font-size: 2em;
    font-weight: bold;
}

.stat.error .stat-value { color: var(--color-error); }
.stat.warning .stat-value { color: #e0a800; }
.stat.info .stat-value { color: var(--color-info); }
.stat.neutral .stat-value { color: var(--color-neutral); }

.stat-label {
    font-size: 0.85em;
    color: #666;
    text-transform: uppercase;
}

/* Tabs */
.tabs {
    display: flex;
    background: #f8f9fa;
    border-bottom: 1px solid #ddd;
}

.tab-btn {
    flex: 1;
    padding: 15px 20px;
    border: none;
    background: none;
    cursor: pointer;
    font-size: 1em;
    color: #666;
    transition: all 0.2s;
}

.tab-btn:hover {
    background: #e9ecef;
}

.tab-btn.active {
    background: white;
    color: #8b5cf6;
    font-weight: bold;
    border-bottom: 3px solid #8b5cf6;
}

.tab-content {
    display: none;
    padding: 20px 30px;
}

.tab-content.active {
    display: block;
}

/* Filters */
.severity-filters {
    display: flex;
    align-items: center;
    gap: 15px;
    margin-bottom: 20px;
    padding: 15px;
    background: #f8f9fa;
    border-radius: 8px;
    flex-wrap: wrap;
}

.filter-label {
    font-weight: 600;
    color: #333;
}

.filter-btn {
    padding: 8px 16px;
    border: 2px solid #ddd;
    background: white;
    border-radius: 20px;
    cursor: pointer;
    transition: all 0.2s;
    font-size: 0.9em;
}

.filter-btn.active {
    border-color: #8b5cf6;
    background: #f3e8ff;
}

.filter-btn:hover {
    border-color: #8b5cf6;
}

/* Expand Controls */
.expand-controls {
    display: flex;
    gap: 10px;
    margin-bottom: 15px;
}

.expand-btn {
    padding: 8px 16px;
    border: 1px solid #ddd;
    background: white;
    border-radius: 4px;
    cursor: pointer;
    font-size: 0.85em;
    transition: all 0.2s;
}

.expand-btn:hover {
    background: #f8f9fa;
    border-color: #8b5cf6;
}

/* File & Rule Sections */
.file-section, .rule-section, .category-section, .rule-file-section {
    background: white;
    border-radius: 8px;
    margin-bottom: 10px;
    border: 1px solid #e0e0e0;
    box-shadow: 0 1px 3px rgba(0,0,0,0.05);
}

.file-section summary, .rule-section summary, .category-section summary, .rule-file-section summary {
    padding: 15px;
    cursor: pointer;
    display: flex;
    align-items: center;
    gap: 15px;
    flex-wrap: wrap;
    transition: background 0.2s;
}

.file-section summary:hover, .rule-section summary:hover, .category-section summary:hover, .rule-file-section summary:hover {
    background: #f8f9fa;
}

.file-path {
    font-weight: 600;
    color: #333;
    word-break: break-all;
}

.rule-id {
    font-weight: 600;
    color: #8b5cf6;
    font-family: 'Consolas', 'Monaco', monospace;
}

.category-name {
    font-weight: 600;
    color: #333;
    font-size: 1.1em;
}

.file-badges, .category-badges {
    margin-left: auto;
    display: flex;
    gap: 5px;
}

.badge {
    display: inline-block;
    padding: 4px 10px;
    border-radius: 12px;
    font-size: 0.75em;
    font-weight: 600;
}

.badge.error { background: var(--color-error-bg); color: var(--color-error); }
.badge.warning { background: var(--color-warning-bg); color: #856404; }
.badge.info { background: var(--color-info-bg); color: #0c5460; }

.rule-count, .category-count {
    color: #666;
    font-size: 0.9em;
}

.rule-help-link {
    text-decoration: none;
    font-size: 1.1em;
    opacity: 0.7;
    transition: opacity 0.2s;
}

.rule-help-link:hover {
    opacity: 1;
}

/* Issues */
.file-issues, .rule-issues, .rule-file-issues, .category-rules {
    padding: 0 15px 15px;
}

.issue {
    padding: 12px 15px;
    margin-top: 10px;
    border-radius: 6px;
    border-left: 4px solid;
}

.issue.error {
    background: var(--color-error-bg);
    border-color: var(--color-error);
}

.issue.warning {
    background: var(--color-warning-bg);
    border-color: #e0a800;
}

.issue.info {
    background: var(--color-info-bg);
    border-color: var(--color-info);
}

.issue-header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 8px;
    flex-wrap: wrap;
}

.line-num {
    font-family: 'Consolas', 'Monaco', monospace;
    color: #666;
    font-size: 0.85em;
    background: rgba(0,0,0,0.05);
    padding: 2px 8px;
    border-radius: 4px;
}

.severity-badge {
    padding: 3px 8px;
    border-radius: 4px;
    font-size: 0.7em;
    font-weight: 700;
    text-transform: uppercase;
}

.severity-badge.error { background: var(--color-error); color: white; }
.severity-badge.warning { background: #e0a800; color: #333; }
.severity-badge.info { background: var(--color-info); color: white; }

.rule-id-small {
    font-family: 'Consolas', 'Monaco', monospace;
    font-size: 0.8em;
    color: #8b5cf6;
}

.issue-message {
    color: #333;
    line-height: 1.5;
}

.no-issues {
    text-align: center;
    padding: 40px;
    color: var(--color-success);
    font-size: 1.3em;
}

/* Statistics */
.statistics-container {
    padding: 20px;
}

.statistics-container h2 {
    color: #8b5cf6;
    margin-bottom: 25px;
    text-align: center;
    font-size: 1.8em;
}

.stats-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 20px;
}

.chart-card {
    background: white;
    border-radius: 12px;
    padding: 20px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    transition: transform 0.2s, box-shadow 0.2s;
}

.chart-card:hover {
    transform: translateY(-3px);
    box-shadow: 0 8px 25px rgba(0,0,0,0.15);
}

.chart-card.wide {
    grid-column: span 2;
}

.chart-card h3 {
    margin: 0 0 15px 0;
    color: #333;
    font-size: 1.1em;
    border-bottom: 2px solid #8b5cf6;
    padding-bottom: 10px;
}

.chart-wrapper {
    position: relative;
    height: 250px;
    display: flex;
    justify-content: center;
    align-items: center;
}

.chart-wrapper-wide {
    position: relative;
    height: 300px;
}

.chart-description {
    text-align: center;
    color: #888;
    font-size: 0.85em;
    margin-top: 10px;
    font-style: italic;
}

.quick-stats {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 15px;
}

.quick-stat {
    background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
    border-radius: 8px;
    padding: 15px;
    text-align: center;
    transition: transform 0.2s;
}

.quick-stat:hover {
    transform: scale(1.02);
}

.quick-stat.error-highlight {
    background: linear-gradient(135deg, #f8d7da 0%, #f5c6cb 100%);
}

.qs-value {
    display: block;
    font-size: 1.8em;
    font-weight: bold;
    color: #8b5cf6;
}

.error-highlight .qs-value {
    color: #dc3545;
}

.qs-label {
    display: block;
    font-size: 0.8em;
    color: #666;
    text-transform: uppercase;
    margin-top: 5px;
}

.health-score-container {
    position: relative;
    height: 200px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}

.health-score-text {
    position: absolute;
    text-align: center;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

.health-value {
    display: block;
    font-size: 2.5em;
    font-weight: bold;
    color: #28a745;
}

.health-label {
    display: block;
    font-size: 0.9em;
    color: #666;
}

@media (max-width: 1024px) {
    .stats-grid {
        grid-template-columns: 1fr;
    }
    
    .chart-card.wide {
        grid-column: span 1;
    }
}

/* Rule Documentation Modal */
.rule-docs-modal {
    display: none;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.5);
    z-index: 1000;
    align-items: center;
    justify-content: center;
}

.rule-docs-modal.show {
    display: flex;
}

.rule-docs-modal-content {
    background: white;
    border-radius: 12px;
    max-width: 800px;
    max-height: 80vh;
    width: 90%;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    box-shadow: 0 10px 40px rgba(0,0,0,0.3);
}

.rule-docs-modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 15px 20px;
    border-bottom: 1px solid #e5e7eb;
    background: linear-gradient(135deg, #8b5cf6 0%, #a855f7 100%);
    color: white;
}

.rule-docs-modal-header h2 {
    font-size: 1.2em;
    margin: 0;
    font-family: 'Consolas', 'Monaco', monospace;
}

.rule-docs-close {
    background: none;
    border: none;
    font-size: 1.5em;
    cursor: pointer;
    color: white;
    opacity: 0.8;
    transition: opacity 0.2s;
}

.rule-docs-close:hover {
    opacity: 1;
}

.rule-docs-modal-body {
    padding: 20px;
    overflow-y: auto;
    line-height: 1.8;
}

.rule-docs-modal-body h1 {
    font-size: 1.5em;
    margin-bottom: 15px;
    color: #8b5cf6;
}

.rule-docs-modal-body h2 {
    font-size: 1.2em;
    margin: 20px 0 10px;
    color: #333;
}

.rule-docs-modal-body p {
    margin-bottom: 15px;
}

.rule-docs-modal-body code {
    background: #f3f4f6;
    padding: 2px 6px;
    border-radius: 4px;
    font-family: 'Consolas', 'Monaco', monospace;
    font-size: 0.9em;
}

.rule-docs-modal-body pre {
    background: #1f2937;
    color: #f9fafb;
    padding: 15px;
    border-radius: 8px;
    overflow-x: auto;
    margin: 15px 0;
    font-family: 'Consolas', 'Monaco', monospace;
}

/* Footer */
footer {
    text-align: center;
    padding: 20px;
    background: #f8f9fa;
    border-top: 1px solid #eee;
    color: #666;
    font-size: 0.9em;
}

/* Hidden class for filtering */
.hidden {
    display: none !important;
}

.hidden-by-filter {
    display: none !important;
}
</style>"""

    def _get_scripts(self) -> str:
        """Get embedded JavaScript."""
        return """<script>
(function() {
    'use strict';
    
    // ==================== Tab Switching ====================
    var tabBtns = document.querySelectorAll('.tab-btn');
    var tabContents = document.querySelectorAll('.tab-content');
    
    for (var i = 0; i < tabBtns.length; i++) {
        tabBtns[i].onclick = function() {
            var tabName = this.getAttribute('data-tab');
            for (var j = 0; j < tabBtns.length; j++) {
                tabBtns[j].classList.remove('active');
            }
            for (var j = 0; j < tabContents.length; j++) {
                tabContents[j].classList.remove('active');
            }
            this.classList.add('active');
            document.getElementById(tabName).classList.add('active');
            
            // Initialize charts when statistics tab is shown
            if (tabName === 'statistics') {
                setTimeout(initializeCharts, 100);
            }
        };
    }
    
    // ==================== Expand/Collapse Controls ====================
    var expandBtns = document.querySelectorAll('.expand-btn');
    
    for (var i = 0; i < expandBtns.length; i++) {
        expandBtns[i].onclick = function(e) {
            e.preventDefault();
            e.stopPropagation();
            
            var action = this.getAttribute('data-action');
            var targetId = this.getAttribute('data-target');
            var container = document.getElementById(targetId);
            
            if (!container) {
                return;
            }
            
            var details = container.querySelectorAll('details');
            
            if (action === 'expand-all') {
                for (var j = 0; j < details.length; j++) {
                    details[j].open = true;
                }
            } else if (action === 'collapse-all') {
                for (var j = 0; j < details.length; j++) {
                    details[j].open = false;
                }
            } else if (action === 'expand-level1') {
                var cats = container.querySelectorAll('.category-section');
                var rules = container.querySelectorAll('.rule-section');
                var files = container.querySelectorAll('.rule-file-section');
                for (var j = 0; j < cats.length; j++) cats[j].open = true;
                for (var j = 0; j < rules.length; j++) rules[j].open = true;
                for (var j = 0; j < files.length; j++) files[j].open = false;
            } else if (action === 'collapse-level1') {
                var cats = container.querySelectorAll('.category-section');
                var rules = container.querySelectorAll('.rule-section');
                for (var j = 0; j < cats.length; j++) cats[j].open = true;
                for (var j = 0; j < rules.length; j++) rules[j].open = false;
            }
        };
    }
    
    // ==================== Severity Filtering ====================
    function applySeverityFilters() {
        var filterBtns = document.querySelectorAll('.filter-btn.active');
        var activeFilters = [];
        for (var i = 0; i < filterBtns.length; i++) {
            activeFilters.push(filterBtns[i].getAttribute('data-severity'));
        }
        
        // Filter individual issues
        var issues = document.querySelectorAll('.issue');
        for (var i = 0; i < issues.length; i++) {
            var severity = issues[i].getAttribute('data-severity');
            if (activeFilters.indexOf(severity) !== -1) {
                issues[i].classList.remove('hidden-by-filter');
            } else {
                issues[i].classList.add('hidden-by-filter');
            }
        }
        
        // Hide file sections with no visible issues (By File tab)
        var fileSections = document.querySelectorAll('#files .file-section');
        for (var i = 0; i < fileSections.length; i++) {
            var section = fileSections[i];
            var visibleIssues = section.querySelectorAll('.issue:not(.hidden-by-filter)');
            if (visibleIssues.length === 0) {
                section.classList.add('hidden-by-filter');
            } else {
                section.classList.remove('hidden-by-filter');
            }
            updateSectionBadges(section, visibleIssues);
        }
        
        // Hide rule-file sections
        var ruleFileSections = document.querySelectorAll('.rule-file-section');
        for (var i = 0; i < ruleFileSections.length; i++) {
            var section = ruleFileSections[i];
            var visibleIssues = section.querySelectorAll('.issue:not(.hidden-by-filter)');
            if (visibleIssues.length === 0) {
                section.classList.add('hidden-by-filter');
            } else {
                section.classList.remove('hidden-by-filter');
            }
            updateSectionBadges(section, visibleIssues);
        }
        
        // Hide rule sections
        var ruleSections = document.querySelectorAll('.rule-section');
        for (var i = 0; i < ruleSections.length; i++) {
            var section = ruleSections[i];
            var visibleFileSections = section.querySelectorAll('.rule-file-section:not(.hidden-by-filter)');
            var visibleIssues = section.querySelectorAll('.issue:not(.hidden-by-filter)');
            if (visibleFileSections.length === 0) {
                section.classList.add('hidden-by-filter');
            } else {
                section.classList.remove('hidden-by-filter');
            }
            var countSpan = section.querySelector('.rule-count');
            if (countSpan) {
                countSpan.innerHTML = generateBadgesHtml(visibleIssues) + ' (' + visibleIssues.length + ' occurrence(s))';
            }
        }
        
        // Hide category sections
        var categorySections = document.querySelectorAll('.category-section');
        for (var i = 0; i < categorySections.length; i++) {
            var section = categorySections[i];
            var visibleRuleSections = section.querySelectorAll('.rule-section:not(.hidden-by-filter)');
            var visibleIssues = section.querySelectorAll('.issue:not(.hidden-by-filter)');
            if (visibleRuleSections.length === 0) {
                section.classList.add('hidden-by-filter');
            } else {
                section.classList.remove('hidden-by-filter');
            }
            var badgesSpan = section.querySelector('.category-badges');
            var countSpan = section.querySelector('.category-count');
            if (badgesSpan) badgesSpan.innerHTML = generateBadgesHtml(visibleIssues);
            if (countSpan) countSpan.textContent = '(' + visibleIssues.length + ' issue(s) in ' + visibleRuleSections.length + ' rule(s))';
        }
        
        // Update summary stats
        var visibleErrors = document.querySelectorAll('#files .issue.error:not(.hidden-by-filter)').length;
        var visibleWarnings = document.querySelectorAll('#files .issue.warning:not(.hidden-by-filter)').length;
        var visibleInfos = document.querySelectorAll('#files .issue.info:not(.hidden-by-filter)').length;
        var totalVisible = visibleErrors + visibleWarnings + visibleInfos;
        
        var errorStat = document.querySelector('.stat.error .stat-value');
        var warningStat = document.querySelector('.stat.warning .stat-value');
        var infoStat = document.querySelector('.stat.info .stat-value');
        
        if (errorStat) errorStat.textContent = visibleErrors;
        if (warningStat) warningStat.textContent = visibleWarnings;
        if (infoStat) infoStat.textContent = visibleInfos;
        
        var statusBadge = document.querySelector('.status-badge');
        if (statusBadge) {
            if (totalVisible === 0) {
                statusBadge.textContent = 'All Clear!';
                statusBadge.className = 'status-badge success';
            } else {
                statusBadge.textContent = totalVisible + ' Issue(s) Found';
                statusBadge.className = 'status-badge ' + (visibleErrors > 0 ? 'error' : 'warning');
            }
        }
        
        var summarySection = document.querySelector('.summary');
        if (summarySection) {
            summarySection.classList.remove('success', 'error', 'warning');
            if (totalVisible === 0) summarySection.classList.add('success');
            else if (visibleErrors > 0) summarySection.classList.add('error');
            else summarySection.classList.add('warning');
        }
        
        if (chartsInitialized) {
            updateChartsWithFilter(visibleErrors, visibleWarnings, visibleInfos);
        }
    }
    
    function updateSectionBadges(section, visibleIssues) {
        var badgesSpan = section.querySelector('.file-badges');
        if (badgesSpan) {
            badgesSpan.innerHTML = generateBadgesHtml(visibleIssues);
        }
    }
    
    function generateBadgesHtml(issues) {
        var errors = 0, warnings = 0, infos = 0;
        for (var i = 0; i < issues.length; i++) {
            if (issues[i].classList.contains('error')) errors++;
            else if (issues[i].classList.contains('warning')) warnings++;
            else if (issues[i].classList.contains('info')) infos++;
        }
        var badges = '';
        if (errors > 0) badges += '<span class="badge error">' + errors + ' E</span>';
        if (warnings > 0) badges += '<span class="badge warning">' + warnings + ' W</span>';
        if (infos > 0) badges += '<span class="badge info">' + infos + ' I</span>';
        return badges;
    }
    
    var filterBtns = document.querySelectorAll('.filter-btn');
    for (var i = 0; i < filterBtns.length; i++) {
        filterBtns[i].onclick = function() {
            this.classList.toggle('active');
            applySeverityFilters();
        };
    }
    
    // Apply filters on page load
    applySeverityFilters();
    
    // ==================== Rule Documentation Modal ====================
    var ruleDocsDataEl = document.getElementById('rule-docs-data');
    var ruleDocsData = ruleDocsDataEl ? JSON.parse(ruleDocsDataEl.textContent) : {};
    
    var helpLinks = document.querySelectorAll('.rule-help-link');
    for (var i = 0; i < helpLinks.length; i++) {
        helpLinks[i].onclick = function(e) {
            e.preventDefault();
            var ruleId = this.getAttribute('data-rule-id');
            showRuleDocsModal(ruleId);
        };
    }
    
    window.showRuleDocsModal = function(ruleId) {
        var modal = document.getElementById('rule-docs-modal');
        var title = document.getElementById('rule-docs-title');
        var body = document.getElementById('rule-docs-body');
        title.textContent = ruleId;
        var content = ruleDocsData[ruleId] || 'No documentation available.';
        body.innerHTML = simpleMarkdown(content);
        modal.classList.add('show');
    };
    
    window.closeRuleDocsModal = function() {
        document.getElementById('rule-docs-modal').classList.remove('show');
    };
    
    var modal = document.getElementById('rule-docs-modal');
    if (modal) {
        modal.onclick = function(e) {
            if (e.target.id === 'rule-docs-modal') closeRuleDocsModal();
        };
    }
    
    function simpleMarkdown(text) {
        return text
            .replace(/^### (.*$)/gm, '<h3>$1</h3>')
            .replace(/^## (.*$)/gm, '<h2>$1</h2>')
            .replace(/^# (.*$)/gm, '<h1>$1</h1>')
            .replace(/\\*\\*(.*?)\\*\\*/g, '<strong>$1</strong>')
            .replace(/\\*(.*?)\\*/g, '<em>$1</em>')
            .replace(/`([^`]+)`/g, '<code>$1</code>')
            .replace(/```([\\s\\S]*?)```/g, '<pre>$1</pre>')
            .replace(/\\n/g, '<br>');
    }
    
    // ==================== Charts (matching original html.py) ====================
    var chartsInitialized = false;
    window.linterCharts = window.linterCharts || {};
    
    var colors = {
        error: '#dc3545',
        warning: '#ffc107',
        info: '#17a2b8',
        primary: '#8b5cf6',
        secondary: '#a855f7',
        success: '#28a745'
    };
    
    function initializeCharts() {
        if (chartsInitialized) return;
        if (typeof Chart === 'undefined') return;
        
        var dataElement = document.getElementById('chart-data');
        if (!dataElement) return;
        
        var data = JSON.parse(dataElement.textContent);
        chartsInitialized = true;
        
        // Severity Pie Chart
        var severityPieCtx = document.getElementById('severityPieChart');
        if (severityPieCtx) {
            window.linterCharts.severityPie = new Chart(severityPieCtx, {
                type: 'pie',
                data: {
                    labels: data.severity.labels,
                    datasets: [{
                        data: data.severity.values,
                        backgroundColor: data.severity.colors,
                        borderWidth: 2,
                        borderColor: '#fff'
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            position: 'bottom',
                            labels: { padding: 15, usePointStyle: true }
                        },
                        tooltip: {
                            callbacks: {
                                label: function(context) {
                                    var total = context.dataset.data.reduce(function(a, b) { return a + b; }, 0);
                                    var percentage = total > 0 ? ((context.raw / total) * 100).toFixed(1) : 0;
                                    return context.label + ': ' + context.raw + ' (' + percentage + '%)';
                                }
                            }
                        }
                    }
                }
            });
        }
        
        // Severity Doughnut Chart
        var doughnutCtx = document.getElementById('severityDoughnutChart');
        if (doughnutCtx) {
            window.linterCharts.severityDoughnut = new Chart(doughnutCtx, {
                type: 'doughnut',
                data: {
                    labels: data.severity.labels,
                    datasets: [{
                        data: data.severity.values,
                        backgroundColor: data.severity.colors,
                        borderWidth: 3,
                        borderColor: '#fff',
                        hoverOffset: 10
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    cutout: '60%',
                    plugins: {
                        legend: {
                            position: 'bottom',
                            labels: { padding: 15, usePointStyle: true }
                        }
                    }
                }
            });
        }
        
        // Category Stacked Bar Chart
        var categoryCtx = document.getElementById('categoryBarChart');
        if (categoryCtx && data.categoryLabels.length > 0) {
            window.linterCharts.categoryBar = new Chart(categoryCtx, {
                type: 'bar',
                data: {
                    labels: data.categoryLabels,
                    datasets: [
                        {
                            label: 'Errors',
                            data: data.categoryErrors,
                            backgroundColor: colors.error,
                            borderRadius: 4
                        },
                        {
                            label: 'Warnings',
                            data: data.categoryWarnings,
                            backgroundColor: colors.warning,
                            borderRadius: 4
                        },
                        {
                            label: 'Info',
                            data: data.categoryInfos,
                            backgroundColor: colors.info,
                            borderRadius: 4
                        }
                    ]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    scales: {
                        x: { stacked: true, grid: { display: false } },
                        y: { stacked: true, beginAtZero: true }
                    },
                    plugins: { legend: { position: 'top' } }
                }
            });
        }
        
        // Top Rules Horizontal Stacked Bar Chart
        var topRulesCtx = document.getElementById('topRulesChart');
        if (topRulesCtx && data.topRuleLabels.length > 0) {
            window.linterCharts.topRules = new Chart(topRulesCtx, {
                type: 'bar',
                data: {
                    labels: data.topRuleLabels,
                    datasets: [
                        {
                            label: 'Errors',
                            data: data.topRuleErrors || [],
                            backgroundColor: colors.error,
                            borderRadius: 0
                        },
                        {
                            label: 'Warnings',
                            data: data.topRuleWarnings || [],
                            backgroundColor: colors.warning,
                            borderRadius: 0
                        },
                        {
                            label: 'Info',
                            data: data.topRuleInfos || [],
                            backgroundColor: colors.info,
                            borderRadius: 0
                        }
                    ]
                },
                options: {
                    indexAxis: 'y',
                    responsive: true,
                    maintainAspectRatio: false,
                    scales: {
                        x: { stacked: true, beginAtZero: true, grid: { color: '#f0f0f0' } },
                        y: { stacked: true, grid: { display: false }, ticks: { font: { family: 'monospace', size: 10 } } }
                    },
                    plugins: {
                        legend: { position: 'top' },
                        tooltip: {
                            callbacks: {
                                title: function(context) {
                                    var idx = context[0].dataIndex;
                                    return data.topRuleLabels[idx];
                                },
                                afterTitle: function(context) {
                                    var idx = context[0].dataIndex;
                                    var errors = data.topRuleErrors ? data.topRuleErrors[idx] : 0;
                                    var warnings = data.topRuleWarnings ? data.topRuleWarnings[idx] : 0;
                                    var infos = data.topRuleInfos ? data.topRuleInfos[idx] : 0;
                                    return 'Total: ' + (errors + warnings + infos) + ' issues';
                                }
                            }
                        }
                    }
                }
            });
        }
        
        // Top Files Stacked Bar Chart
        var topFilesCtx = document.getElementById('topFilesChart');
        if (topFilesCtx && data.topFileLabels.length > 0) {
            window.linterCharts.topFiles = new Chart(topFilesCtx, {
                type: 'bar',
                data: {
                    labels: data.topFileLabels,
                    datasets: [
                        {
                            label: 'Errors',
                            data: data.topFileErrors || [],
                            backgroundColor: colors.error,
                            borderRadius: 0
                        },
                        {
                            label: 'Warnings',
                            data: data.topFileWarnings || [],
                            backgroundColor: colors.warning,
                            borderRadius: 0
                        },
                        {
                            label: 'Info',
                            data: data.topFileInfos || [],
                            backgroundColor: colors.info,
                            borderRadius: 0
                        }
                    ]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    scales: {
                        y: { stacked: true, beginAtZero: true },
                        x: {
                            stacked: true,
                            ticks: { maxRotation: 45, minRotation: 45, font: { size: 9 } }
                        }
                    },
                    plugins: {
                        legend: { position: 'top' },
                        tooltip: {
                            callbacks: {
                                afterTitle: function(context) {
                                    var idx = context[0].dataIndex;
                                    var errors = data.topFileErrors ? data.topFileErrors[idx] : 0;
                                    var warnings = data.topFileWarnings ? data.topFileWarnings[idx] : 0;
                                    var infos = data.topFileInfos ? data.topFileInfos[idx] : 0;
                                    return 'Total: ' + (errors + warnings + infos) + ' issues';
                                }
                            }
                        }
                    }
                }
            });
        }
        
        // Health Gauge Chart
        var healthCtx = document.getElementById('healthGauge');
        if (healthCtx) {
            var errorWeight = 10;
            var warningWeight = 3;
            var infoWeight = 1;
            
            var infos = data.infos || (data.totalIssues - data.errors - data.warnings);
            var weightedScore = (data.errors * errorWeight) + (data.warnings * warningWeight) + (infos * infoWeight);
            
            var maxExpectedScore = data.filesScanned * 50;
            var healthScore = Math.max(0, 100 - (weightedScore / Math.max(maxExpectedScore, 1)) * 100);
            healthScore = Math.min(100, Math.round(healthScore));
            
            var healthValueEl = document.getElementById('healthValue');
            if (healthValueEl) {
                healthValueEl.textContent = healthScore;
                if (healthScore >= 80) healthValueEl.style.color = '#28a745';
                else if (healthScore >= 50) healthValueEl.style.color = '#ffc107';
                else healthValueEl.style.color = '#dc3545';
            }
            
            window.linterCharts.healthGauge = new Chart(healthCtx, {
                type: 'doughnut',
                data: {
                    datasets: [{
                        data: [healthScore, 100 - healthScore],
                        backgroundColor: [
                            healthScore >= 80 ? '#28a745' : healthScore >= 50 ? '#ffc107' : '#dc3545',
                            '#e9ecef'
                        ],
                        borderWidth: 0,
                        circumference: 180,
                        rotation: 270
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    cutout: '75%',
                    plugins: {
                        legend: { display: false },
                        tooltip: { enabled: false }
                    }
                }
            });
        }
    }
    
    function updateChartsWithFilter(errors, warnings, infos) {
        var charts = window.linterCharts;
        if (!charts) return;
        
        var dataElement = document.getElementById('chart-data');
        var originalData = dataElement ? JSON.parse(dataElement.textContent) : null;
        var totalIssues = errors + warnings + infos;
        
        // Update pie chart
        if (charts.severityPie) {
            charts.severityPie.data.datasets[0].data = [errors, warnings, infos];
            charts.severityPie.update('none');
        }
        
        // Update doughnut chart
        if (charts.severityDoughnut) {
            charts.severityDoughnut.data.datasets[0].data = [errors, warnings, infos];
            charts.severityDoughnut.update('none');
        }
        
        // Recalculate category data from visible issues
        var categoryData = {};
        var visibleCategorySections = document.querySelectorAll('.category-section:not(.hidden-by-filter)');
        for (var i = 0; i < visibleCategorySections.length; i++) {
            var cat = visibleCategorySections[i];
            var catName = cat.querySelector('.category-name');
            if (catName) {
                var name = catName.textContent.replace(/^[📁\\s]+/, '').trim();
                var catIssues = cat.querySelectorAll('.issue:not(.hidden-by-filter)');
                var catErrors = 0, catWarnings = 0, catInfos = 0;
                for (var j = 0; j < catIssues.length; j++) {
                    if (catIssues[j].classList.contains('error')) catErrors++;
                    else if (catIssues[j].classList.contains('warning')) catWarnings++;
                    else if (catIssues[j].classList.contains('info')) catInfos++;
                }
                if (catErrors + catWarnings + catInfos > 0) {
                    categoryData[name] = { errors: catErrors, warnings: catWarnings, infos: catInfos };
                }
            }
        }
        
        // Update category bar chart
        if (charts.categoryBar) {
            var catLabels = Object.keys(categoryData);
            var catErrors = [], catWarnings = [], catInfos = [];
            for (var i = 0; i < catLabels.length; i++) {
                catErrors.push(categoryData[catLabels[i]].errors);
                catWarnings.push(categoryData[catLabels[i]].warnings);
                catInfos.push(categoryData[catLabels[i]].infos);
            }
            charts.categoryBar.data.labels = catLabels;
            charts.categoryBar.data.datasets[0].data = catErrors;
            charts.categoryBar.data.datasets[1].data = catWarnings;
            charts.categoryBar.data.datasets[2].data = catInfos;
            charts.categoryBar.update('none');
        }
        
        // Recalculate top rules data from visible issues
        var ruleData = {};
        var visibleRuleSections = document.querySelectorAll('.rule-section:not(.hidden-by-filter)');
        for (var i = 0; i < visibleRuleSections.length; i++) {
            var rule = visibleRuleSections[i];
            var ruleIdEl = rule.querySelector('.rule-id');
            if (ruleIdEl) {
                var ruleId = ruleIdEl.textContent.trim();
                var ruleIssues = rule.querySelectorAll('.issue:not(.hidden-by-filter)');
                var ruleErrors = 0, ruleWarnings = 0, ruleInfos = 0;
                for (var j = 0; j < ruleIssues.length; j++) {
                    if (ruleIssues[j].classList.contains('error')) ruleErrors++;
                    else if (ruleIssues[j].classList.contains('warning')) ruleWarnings++;
                    else if (ruleIssues[j].classList.contains('info')) ruleInfos++;
                }
                var ruleTotal = ruleErrors + ruleWarnings + ruleInfos;
                if (ruleTotal > 0) {
                    ruleData[ruleId] = { total: ruleTotal, errors: ruleErrors, warnings: ruleWarnings, infos: ruleInfos };
                }
            }
        }
        
        // Sort by total and take top 15
        var sortedRules = Object.keys(ruleData).sort(function(a, b) {
            return ruleData[b].total - ruleData[a].total;
        }).slice(0, 15);
        
        // Update top rules chart
        if (charts.topRules) {
            var ruleLabels = sortedRules;
            var ruleErrors = [], ruleWarnings = [], ruleInfos = [];
            for (var i = 0; i < sortedRules.length; i++) {
                ruleErrors.push(ruleData[sortedRules[i]].errors);
                ruleWarnings.push(ruleData[sortedRules[i]].warnings);
                ruleInfos.push(ruleData[sortedRules[i]].infos);
            }
            charts.topRules.data.labels = ruleLabels;
            charts.topRules.data.datasets[0].data = ruleErrors;
            charts.topRules.data.datasets[1].data = ruleWarnings;
            charts.topRules.data.datasets[2].data = ruleInfos;
            charts.topRules.update('none');
        }
        
        // Recalculate top files data from visible issues
        var fileData = {};
        var visibleFileSections = document.querySelectorAll('#files .file-section:not(.hidden-by-filter)');
        for (var i = 0; i < visibleFileSections.length; i++) {
            var fileSec = visibleFileSections[i];
            var filePathEl = fileSec.querySelector('.file-path');
            if (filePathEl) {
                var fullPath = filePathEl.textContent.trim();
                var fileName = fullPath.split('/').pop();
                var fileIssues = fileSec.querySelectorAll('.issue:not(.hidden-by-filter)');
                var fileErrors = 0, fileWarnings = 0, fileInfos = 0;
                for (var j = 0; j < fileIssues.length; j++) {
                    if (fileIssues[j].classList.contains('error')) fileErrors++;
                    else if (fileIssues[j].classList.contains('warning')) fileWarnings++;
                    else if (fileIssues[j].classList.contains('info')) fileInfos++;
                }
                var fileTotal = fileErrors + fileWarnings + fileInfos;
                if (fileTotal > 0) {
                    fileData[fileName] = { total: fileTotal, errors: fileErrors, warnings: fileWarnings, infos: fileInfos };
                }
            }
        }
        
        // Sort by total and take top 10
        var sortedFiles = Object.keys(fileData).sort(function(a, b) {
            return fileData[b].total - fileData[a].total;
        }).slice(0, 10);
        
        // Update top files chart
        if (charts.topFiles) {
            var fileLabels = sortedFiles;
            var fileErrors = [], fileWarnings = [], fileInfos = [];
            for (var i = 0; i < sortedFiles.length; i++) {
                fileErrors.push(fileData[sortedFiles[i]].errors);
                fileWarnings.push(fileData[sortedFiles[i]].warnings);
                fileInfos.push(fileData[sortedFiles[i]].infos);
            }
            charts.topFiles.data.labels = fileLabels;
            charts.topFiles.data.datasets[0].data = fileErrors;
            charts.topFiles.data.datasets[1].data = fileWarnings;
            charts.topFiles.data.datasets[2].data = fileInfos;
            charts.topFiles.update('none');
        }
        
        // Update health gauge
        if (charts.healthGauge && originalData) {
            var errorWeight = 10;
            var warningWeight = 3;
            var infoWeight = 1;
            
            var weightedScore = (errors * errorWeight) + (warnings * warningWeight) + (infos * infoWeight);
            var maxExpectedScore = originalData.filesScanned * 50;
            var healthScore = Math.max(0, 100 - (weightedScore / Math.max(maxExpectedScore, 1)) * 100);
            healthScore = Math.min(100, Math.round(healthScore));
            
            charts.healthGauge.data.datasets[0].data = [healthScore, 100 - healthScore];
            charts.healthGauge.data.datasets[0].backgroundColor[0] = 
                healthScore >= 80 ? '#28a745' : healthScore >= 50 ? '#ffc107' : '#dc3545';
            charts.healthGauge.update('none');
            
            var healthValueEl = document.getElementById('healthValue');
            if (healthValueEl) {
                healthValueEl.textContent = healthScore;
                healthValueEl.style.color = healthScore >= 80 ? '#28a745' : healthScore >= 50 ? '#ffc107' : '#dc3545';
            }
        }
        
        // Update ALL quick stats
        var filesWithIssues = Object.keys(fileData).length;
        var rulesTriggered = Object.keys(ruleData).length;
        var categoriesAffected = Object.keys(categoryData).length;
        var avgIssuesPerFile = filesWithIssues > 0 ? (totalIssues / filesWithIssues).toFixed(1) : '0.0';
        var errorRate = totalIssues > 0 ? ((errors / totalIssues) * 100).toFixed(1) : '0.0';
        
        var qsTotalIssues = document.getElementById('qs-total-issues');
        if (qsTotalIssues) qsTotalIssues.textContent = totalIssues;
        
        var qsFilesWithIssues = document.getElementById('qs-files-with-issues');
        if (qsFilesWithIssues) qsFilesWithIssues.textContent = filesWithIssues;
        
        var qsRulesTriggered = document.getElementById('qs-rules-triggered');
        if (qsRulesTriggered) qsRulesTriggered.textContent = rulesTriggered;
        
        var qsCategoriesAffected = document.getElementById('qs-categories-affected');
        if (qsCategoriesAffected) qsCategoriesAffected.textContent = categoriesAffected;
        
        var qsAvgIssuesFile = document.getElementById('qs-avg-issues-file');
        if (qsAvgIssuesFile) qsAvgIssuesFile.textContent = avgIssuesPerFile;
        
        var qsErrorRate = document.getElementById('qs-error-rate');
        if (qsErrorRate) qsErrorRate.textContent = errorRate + '%';
    }
    
})();
</script>"""
