"""
HTML output formatter for oelint-adv reports.

Generates a standalone HTML report for oelint-adv results with:
- Summary dashboard
- Per-file issue breakdown
- Per-rule grouping
- Color-coded severities
- Expandable sections
- Rule documentation viewer

This is Option B implementation - a separate file alongside the main report.

(c) 2024-2026 Eduardo Correia <ecorreia@apliant.com.br>
All rights reserved.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional, TextIO, TYPE_CHECKING
from collections import defaultdict
import html
import json

if TYPE_CHECKING:
    from bake_linter.core.oelint_integration import OelintResult, OelintSummary


class OelintHtmlFormatter:
    """
    HTML formatter for oelint-adv reports.
    
    Generates a self-contained HTML file with embedded CSS and JavaScript
    for an interactive oelint-adv report.
    """

    def __init__(
        self,
        output: Optional[TextIO] = None,
        verbose: bool = False,
        title: str = "oelint-adv Report",
    ):
        self.output = output
        self.verbose = verbose
        self.title = title

    def format_results(
        self,
        results: List["OelintResult"],
        summary: "OelintSummary",
    ) -> str:
        """Generate HTML report for oelint-adv results."""
        # Group results by file
        by_file: Dict[Path, List["OelintResult"]] = defaultdict(list)
        for result in results:
            by_file[result.file].append(result)
        
        # Group results by rule
        by_rule: Dict[str, List["OelintResult"]] = defaultdict(list)
        for result in results:
            by_rule[result.rule_id].append(result)
        
        # Group rules by category (rule_group)
        rule_categories: Dict[str, str] = {}
        for result in results:
            rule_categories[result.rule_id] = result.rule_group.upper()
        
        return self._render_html(results, summary, by_file, by_rule, rule_categories)

    def write(
        self,
        results: List["OelintResult"],
        summary: "OelintSummary",
    ) -> None:
        """Format and write results to output."""
        formatted = self.format_results(results, summary)
        if self.output:
            self.output.write(formatted)
            if not formatted.endswith("\n"):
                self.output.write("\n")

    def _render_html(
        self,
        results: List["OelintResult"],
        summary: "OelintSummary",
        by_file: Dict[Path, List["OelintResult"]],
        by_rule: Dict[str, List["OelintResult"]],
        rule_categories: Dict[str, str],
    ) -> str:
        """Render the complete HTML document."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        version_info = f"Version: {summary.tool_version}" if summary.tool_version else ""
        
        return f"""<!DOCTYPE html>
<!--
    oelint-adv Report (generated by Bake Linter)
    (c) 2024-2026 Eduardo Correia <ecorreia@apliant.com.br>
    All rights reserved.
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(self.title)}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
    {self._get_styles()}
</head>
<body>
    <div class="container">
        <header>
            <h1>🔍 {html.escape(self.title)}</h1>
            <p class="timestamp">Generated: {timestamp}</p>
            <p class="version-info">{version_info}</p>
            <div class="copyright-section">
                <!-- START: DO NOT REMOVE OR MODIFY THIS COPYRIGHT NOTICE -->
                <p class="copyright-main">© 2024-2026 <a href="https://www.apliant.com.br/cv" target="_blank" class="author-link">Eduardo Correia</a> — <a href="https://www.apliant.com.br/cv" target="_blank" class="cv-link">📄 Curriculum Vitae</a></p>
                <p class="copyright-links">
                    <a href="mailto:ecorreia@apliant.com.br" class="contact-link">📧 ecorreia@apliant.com.br</a>
                    <span class="link-separator">•</span>
                    <a href="https://www.apliant.com.br" target="_blank" class="contact-link">🌐 www.apliant.com.br</a>
                    <span class="link-separator">•</span>
                    <a href="https://www.linkedin.com/in/c99-eduardo/" target="_blank" class="contact-link linkedin-link">💼 LinkedIn</a>
                </p>
                <p class="tool-info">Results from <a href="https://github.com/priv-kweihmann/oelint-adv" target="_blank">oelint-adv</a> - Advanced OELint for Yocto/OpenEmbedded</p>
                <!-- END: DO NOT REMOVE OR MODIFY THIS COPYRIGHT NOTICE -->
            </div>
        </header>
        
        {self._render_summary(summary)}
        
        <nav class="tabs">
            <button class="tab-btn" data-tab="files">📁 By File</button>
            <button class="tab-btn active" data-tab="rules">📋 By Rule</button>
            <button class="tab-btn" data-tab="statistics">📊 Statistics</button>
        </nav>
        
        <div class="severity-filters">
            <span class="filter-label">Filter by Severity:</span>
            <button class="filter-btn active" data-severity="error">🔴 Errors</button>
            <button class="filter-btn active" data-severity="warning">🟡 Warnings</button>
            <button class="filter-btn active" data-severity="info">🔵 Info</button>
        </div>
        
        <div id="files" class="tab-content">
            <div class="expand-controls">
                <button class="expand-btn" data-action="expand-all" data-target="files">▼ Expand All</button>
                <button class="expand-btn" data-action="collapse-all" data-target="files">▲ Collapse All</button>
            </div>
            {self._render_files_section(by_file)}
        </div>
        
        <div id="rules" class="tab-content active">
            <div class="expand-controls">
                <button class="expand-btn" data-action="expand-all" data-target="rules">▼▼ Items</button>
                <button class="expand-btn" data-action="expand-level1" data-target="rules">▲ Files</button>
                <button class="expand-btn" data-action="collapse-level1" data-target="rules">▲▲ Rules</button>
                <button class="expand-btn" data-action="collapse-all" data-target="rules">▲▲▲ Categories</button>
            </div>
            {self._render_rules_section(by_rule, rule_categories)}
        </div>
        
        <div id="statistics" class="tab-content">
            {self._render_statistics_section(summary, by_rule, by_file, rule_categories)}
        </div>
        
        <footer>
            <p>oelint-adv Report • {summary.total_issues} issue(s) in {summary.files_scanned} file(s)</p>
        </footer>
    </div>
    
    <!-- Rule Documentation Modal -->
    <div id="rule-docs-modal" class="rule-docs-modal">
        <div class="rule-docs-modal-content">
            <div class="rule-docs-modal-header">
                <h2 id="rule-docs-title">Rule Documentation</h2>
                <button class="rule-docs-close" onclick="closeRuleDocsModal()">&times;</button>
            </div>
            <div id="rule-docs-body" class="rule-docs-modal-body">
                <p>Loading documentation...</p>
            </div>
        </div>
    </div>
    
    <!-- Rule Documentation Data -->
    <script id="rule-docs-data" type="application/json">{self._get_rule_docs_data(by_rule)}</script>
    
    {self._get_scripts()}
</body>
</html>"""

    def _render_summary(self, summary: "OelintSummary") -> str:
        """Render the summary dashboard."""
        status_class = "success" if summary.total_issues == 0 else (
            "error" if summary.errors > 0 else "warning"
        )
        status_text = "All Clear!" if summary.total_issues == 0 else (
            f"{summary.total_issues} Issue(s) Found"
        )
        
        return f"""
        <section class="summary {status_class}">
            <div class="summary-header">
                <span class="status-badge {status_class}">{status_text}</span>
            </div>
            <div class="summary-stats">
                <div class="stat error">
                    <span class="stat-value">{summary.errors}</span>
                    <span class="stat-label">Errors</span>
                </div>
                <div class="stat warning">
                    <span class="stat-value">{summary.warnings}</span>
                    <span class="stat-label">Warnings</span>
                </div>
                <div class="stat info">
                    <span class="stat-value">{summary.infos}</span>
                    <span class="stat-label">Info</span>
                </div>
                <div class="stat neutral">
                    <span class="stat-value">{summary.files_scanned}</span>
                    <span class="stat-label">Files Scanned</span>
                </div>
                <div class="stat neutral">
                    <span class="stat-value">{len(summary.rules_triggered)}</span>
                    <span class="stat-label">Rules Triggered</span>
                </div>
            </div>
        </section>"""

    def _render_files_section(self, by_file: Dict[Path, List["OelintResult"]]) -> str:
        """Render the files section."""
        if not by_file:
            return '<p class="no-issues">✓ No issues found in any files!</p>'
        
        sections = []
        for file_path in sorted(by_file.keys()):
            file_results = sorted(by_file[file_path], key=lambda r: r.line)
            
            error_count = sum(1 for r in file_results if r.severity == 'error')
            warning_count = sum(1 for r in file_results if r.severity == 'warning')
            info_count = sum(1 for r in file_results if r.severity == 'info')
            
            badges = []
            if error_count:
                badges.append(f'<span class="badge error">{error_count} E</span>')
            if warning_count:
                badges.append(f'<span class="badge warning">{warning_count} W</span>')
            if info_count:
                badges.append(f'<span class="badge info">{info_count} I</span>')
            
            issues_html = "\n".join(self._render_result(r) for r in file_results)
            
            sections.append(f"""
            <details class="file-section" open>
                <summary>
                    <span class="file-path">{html.escape(str(file_path))}</span>
                    <span class="file-badges">{' '.join(badges)}</span>
                </summary>
                <div class="file-issues">
                    {issues_html}
                </div>
            </details>""")
        
        return "\n".join(sections)

    def _render_rules_section(
        self,
        by_rule: Dict[str, List["OelintResult"]],
        rule_categories: Dict[str, str],
    ) -> str:
        """Render the rules section with category grouping."""
        if not by_rule:
            return '<p class="no-issues">✓ No issues found!</p>'
        
        # Group rules by category
        by_category: Dict[str, Dict[str, List["OelintResult"]]] = defaultdict(dict)
        for rule_id, rule_results in by_rule.items():
            category = rule_categories.get(rule_id, 'OTHER')
            by_category[category][rule_id] = rule_results
        
        category_sections = []
        for category in sorted(by_category.keys()):
            rules_in_category = by_category[category]
            
            # Calculate category totals
            cat_errors = sum(sum(1 for r in results if r.severity == 'error') for results in rules_in_category.values())
            cat_warnings = sum(sum(1 for r in results if r.severity == 'warning') for results in rules_in_category.values())
            cat_infos = sum(sum(1 for r in results if r.severity == 'info') for results in rules_in_category.values())
            cat_total = cat_errors + cat_warnings + cat_infos
            
            cat_badges = []
            if cat_errors:
                cat_badges.append(f'<span class="badge error">{cat_errors} E</span>')
            if cat_warnings:
                cat_badges.append(f'<span class="badge warning">{cat_warnings} W</span>')
            if cat_infos:
                cat_badges.append(f'<span class="badge info">{cat_infos} I</span>')
            
            rule_sections = []
            for rule_id in sorted(rules_in_category.keys()):
                rule_results = rules_in_category[rule_id]
                
                error_count = sum(1 for r in rule_results if r.severity == 'error')
                warning_count = sum(1 for r in rule_results if r.severity == 'warning')
                info_count = sum(1 for r in rule_results if r.severity == 'info')
                
                badges = []
                if error_count:
                    badges.append(f'<span class="badge error">{error_count}</span>')
                if warning_count:
                    badges.append(f'<span class="badge warning">{warning_count}</span>')
                if info_count:
                    badges.append(f'<span class="badge info">{info_count}</span>')
                
                # Group by file within rule
                results_by_file: Dict[Path, List["OelintResult"]] = defaultdict(list)
                for r in rule_results:
                    results_by_file[r.file].append(r)
                
                file_sections = []
                for file_path in sorted(results_by_file.keys()):
                    file_results = sorted(results_by_file[file_path], key=lambda r: r.line)
                    issues_html = "\n".join(self._render_result(r) for r in file_results)
                    
                    file_error_count = sum(1 for r in file_results if r.severity == 'error')
                    file_warning_count = sum(1 for r in file_results if r.severity == 'warning')
                    file_info_count = sum(1 for r in file_results if r.severity == 'info')
                    
                    file_badges = []
                    if file_error_count:
                        file_badges.append(f'<span class="badge error">{file_error_count} E</span>')
                    if file_warning_count:
                        file_badges.append(f'<span class="badge warning">{file_warning_count} W</span>')
                    if file_info_count:
                        file_badges.append(f'<span class="badge info">{file_info_count} I</span>')
                    
                    file_sections.append(f"""
                    <details class="rule-file-section" open>
                        <summary>
                            <span class="file-path">📄 {html.escape(str(file_path))}</span>
                            <span class="file-badges">{' '.join(file_badges)}</span>
                        </summary>
                        <div class="rule-file-issues">
                            {issues_html}
                        </div>
                    </details>""")
                
                files_html = "\n".join(file_sections)
                
                # Help link for rule documentation
                help_link = f'<a href="#" class="rule-help-link" data-rule-id="{html.escape(rule_id)}" title="View rule documentation">❓</a>'
                
                rule_sections.append(f"""
                <details class="rule-section" open>
                    <summary>
                        <span class="rule-id">{html.escape(rule_id)}</span>
                        {help_link}
                        <span class="rule-count">{' '.join(badges)} ({len(rule_results)} occurrence(s))</span>
                    </summary>
                    <div class="rule-issues">
                        {files_html}
                    </div>
                </details>""")
            
            rules_html = "\n".join(rule_sections)
            
            category_sections.append(f"""
            <details class="category-section" open>
                <summary>
                    <span class="category-name">📁 {html.escape(category)}</span>
                    <span class="category-badges">{' '.join(cat_badges)}</span>
                    <span class="category-count">({cat_total} issue(s) in {len(rules_in_category)} rule(s))</span>
                </summary>
                <div class="category-rules">
                    {rules_html}
                </div>
            </details>""")
        
        return "\n".join(category_sections)

    def _render_result(self, result: "OelintResult") -> str:
        """Render a single result."""
        severity_class = result.severity
        
        line_info = f'<span class="line-num">Line {result.line}</span>' if result.line else ""
        
        return f"""
        <div class="issue {severity_class}" data-severity="{severity_class}">
            <div class="issue-header">
                {line_info}
                <span class="severity-badge {severity_class}">{result.severity.upper()}</span>
                <span class="rule-id-small">{html.escape(result.rule_id)}</span>
            </div>
            <div class="issue-message">{html.escape(result.message)}</div>
        </div>"""

    def _render_statistics_section(
        self,
        summary: "OelintSummary",
        by_rule: Dict[str, List["OelintResult"]],
        by_file: Dict[Path, List["OelintResult"]],
        rule_categories: Dict[str, str],
    ) -> str:
        """Render the statistics section with charts."""
        # Severity distribution data
        severity_data = json.dumps({
            "labels": ["Errors", "Warnings", "Info"],
            "data": [summary.errors, summary.warnings, summary.infos],
            "colors": ["#ef4444", "#f59e0b", "#3b82f6"]
        })
        
        # Top rules data (top 10)
        top_rules = sorted(by_rule.items(), key=lambda x: len(x[1]), reverse=True)[:10]
        top_rules_data = json.dumps({
            "labels": [rule_id for rule_id, _ in top_rules],
            "data": [len(results) for _, results in top_rules],
        })
        
        # Category distribution
        category_counts: Dict[str, int] = defaultdict(int)
        for rule_id, results in by_rule.items():
            category = rule_categories.get(rule_id, 'OTHER')
            category_counts[category] += len(results)
        
        category_data = json.dumps({
            "labels": list(category_counts.keys()),
            "data": list(category_counts.values()),
        })
        
        # Top files data (top 10)
        top_files = sorted(by_file.items(), key=lambda x: len(x[1]), reverse=True)[:10]
        top_files_data = json.dumps({
            "labels": [str(f.name) for f, _ in top_files],
            "data": [len(results) for _, results in top_files],
        })
        
        return f"""
        <div class="statistics-grid">
            <div class="chart-container">
                <h3>Severity Distribution</h3>
                <canvas id="severity-chart"></canvas>
            </div>
            <div class="chart-container">
                <h3>Top Rules</h3>
                <canvas id="top-rules-chart"></canvas>
            </div>
            <div class="chart-container">
                <h3>Issues by Category</h3>
                <canvas id="category-chart"></canvas>
            </div>
            <div class="chart-container">
                <h3>Top Files with Issues</h3>
                <canvas id="top-files-chart"></canvas>
            </div>
        </div>
        <script>
            const severityData = {severity_data};
            const topRulesData = {top_rules_data};
            const categoryData = {category_data};
            const topFilesData = {top_files_data};
        </script>"""

    def _get_rule_docs_data(self, by_rule: Dict[str, List["OelintResult"]]) -> str:
        """Get rule documentation data as JSON for embedding."""
        from bake_linter.core.oelint_integration import get_oelint_integration
        
        integration = get_oelint_integration()
        docs = {}
        
        for rule_id in by_rule.keys():
            doc_content = integration.get_rule_documentation(rule_id)
            if doc_content:
                docs[rule_id] = doc_content
            else:
                # Provide a default message
                docs[rule_id] = f"# {rule_id}\n\nNo documentation available for this rule.\n\nPlease refer to the oelint-adv documentation at: https://github.com/priv-kweihmann/oelint-adv"
        
        return json.dumps(docs)

    def _get_styles(self) -> str:
        """Get embedded CSS styles."""
        return """<style>
:root {
    --color-error: #ef4444;
    --color-error-bg: #fef2f2;
    --color-warning: #f59e0b;
    --color-warning-bg: #fffbeb;
    --color-info: #3b82f6;
    --color-info-bg: #eff6ff;
    --color-success: #10b981;
    --color-success-bg: #ecfdf5;
    --color-neutral: #6b7280;
    --color-neutral-bg: #f3f4f6;
    --color-purple: #8b5cf6;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: #1f2937;
    background: #f9fafb;
}

.container {
    max-width: 1400px;
    margin: 0 auto;
    padding: 2rem;
}

header {
    text-align: center;
    margin-bottom: 2rem;
    padding-bottom: 1rem;
    border-bottom: 2px solid #e5e7eb;
}

header h1 {
    font-size: 2rem;
    color: #8b5cf6;
    margin-bottom: 0.5rem;
}

.timestamp, .version-info {
    color: #6b7280;
    font-size: 0.9rem;
}

.copyright-section {
    margin-top: 1rem;
    font-size: 0.85rem;
    color: #6b7280;
}

.copyright-main {
    margin-bottom: 0.3rem;
}

.tool-info {
    margin-top: 0.5rem;
    font-style: italic;
}

.author-link, .cv-link, .contact-link {
    color: #8b5cf6;
    text-decoration: none;
}

.author-link:hover, .cv-link:hover, .contact-link:hover {
    text-decoration: underline;
}

.link-separator {
    margin: 0 0.5rem;
    color: #d1d5db;
}

/* Summary Section */
.summary {
    background: white;
    border-radius: 12px;
    padding: 1.5rem;
    margin-bottom: 2rem;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

.summary.success { border-left: 4px solid var(--color-success); }
.summary.warning { border-left: 4px solid var(--color-warning); }
.summary.error { border-left: 4px solid var(--color-error); }

.summary-header {
    display: flex;
    justify-content: center;
    margin-bottom: 1rem;
}

.status-badge {
    padding: 0.5rem 1.5rem;
    border-radius: 20px;
    font-weight: 600;
    font-size: 1.1rem;
}

.status-badge.success { background: var(--color-success-bg); color: var(--color-success); }
.status-badge.warning { background: var(--color-warning-bg); color: var(--color-warning); }
.status-badge.error { background: var(--color-error-bg); color: var(--color-error); }

.summary-stats {
    display: flex;
    justify-content: center;
    gap: 2rem;
    flex-wrap: wrap;
}

.stat {
    text-align: center;
    padding: 1rem;
    min-width: 100px;
}

.stat-value {
    display: block;
    font-size: 2rem;
    font-weight: 700;
}

.stat-label {
    font-size: 0.85rem;
    color: #6b7280;
    text-transform: uppercase;
}

.stat.error .stat-value { color: var(--color-error); }
.stat.warning .stat-value { color: var(--color-warning); }
.stat.info .stat-value { color: var(--color-info); }
.stat.neutral .stat-value { color: var(--color-neutral); }

/* Tabs */
.tabs {
    display: flex;
    gap: 0.5rem;
    margin-bottom: 1rem;
    border-bottom: 2px solid #e5e7eb;
    padding-bottom: 0.5rem;
}

.tab-btn {
    padding: 0.75rem 1.5rem;
    border: none;
    background: transparent;
    cursor: pointer;
    font-size: 1rem;
    color: #6b7280;
    border-radius: 8px 8px 0 0;
    transition: all 0.2s;
}

.tab-btn:hover { background: #f3f4f6; }
.tab-btn.active {
    background: #8b5cf6;
    color: white;
}

.tab-content { display: none; }
.tab-content.active { display: block; }

/* Filters */
.severity-filters {
    display: flex;
    align-items: center;
    gap: 1rem;
    margin-bottom: 1rem;
    padding: 1rem;
    background: white;
    border-radius: 8px;
    flex-wrap: wrap;
}

.filter-label {
    font-weight: 500;
    color: #374151;
}

.filter-btn {
    padding: 0.5rem 1rem;
    border: 2px solid #e5e7eb;
    background: white;
    border-radius: 20px;
    cursor: pointer;
    transition: all 0.2s;
}

.filter-btn.active {
    border-color: #8b5cf6;
    background: #f5f3ff;
}

.filter-btn:hover { border-color: #8b5cf6; }

/* Expand Controls */
.expand-controls {
    display: flex;
    gap: 0.5rem;
    margin-bottom: 1rem;
}

.expand-btn {
    padding: 0.5rem 1rem;
    border: 1px solid #e5e7eb;
    background: white;
    border-radius: 4px;
    cursor: pointer;
    font-size: 0.85rem;
}

.expand-btn:hover { background: #f3f4f6; }

/* File & Rule Sections */
.file-section, .rule-section, .category-section, .rule-file-section {
    background: white;
    border-radius: 8px;
    margin-bottom: 0.5rem;
    border: 1px solid #e5e7eb;
}

.file-section summary, .rule-section summary, .category-section summary, .rule-file-section summary {
    padding: 1rem;
    cursor: pointer;
    display: flex;
    align-items: center;
    gap: 1rem;
    flex-wrap: wrap;
}

.file-section summary:hover, .rule-section summary:hover, .category-section summary:hover {
    background: #f9fafb;
}

.file-path, .rule-id, .category-name {
    font-weight: 600;
    color: #1f2937;
}

.rule-id { color: #8b5cf6; font-family: monospace; }

.file-badges, .category-badges { margin-left: auto; }

.badge {
    display: inline-block;
    padding: 0.25rem 0.5rem;
    border-radius: 12px;
    font-size: 0.75rem;
    font-weight: 600;
    margin-left: 0.25rem;
}

.badge.error { background: var(--color-error-bg); color: var(--color-error); }
.badge.warning { background: var(--color-warning-bg); color: var(--color-warning); }
.badge.info { background: var(--color-info-bg); color: var(--color-info); }

.rule-count, .category-count {
    color: #6b7280;
    font-size: 0.9rem;
}

.rule-help-link {
    text-decoration: none;
    font-size: 1rem;
}

/* Issues */
.file-issues, .rule-issues, .rule-file-issues, .category-rules {
    padding: 0 1rem 1rem;
}

.issue {
    padding: 0.75rem;
    margin-top: 0.5rem;
    border-radius: 6px;
    border-left: 3px solid;
}

.issue.error { background: var(--color-error-bg); border-color: var(--color-error); }
.issue.warning { background: var(--color-warning-bg); border-color: var(--color-warning); }
.issue.info { background: var(--color-info-bg); border-color: var(--color-info); }

.issue-header {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    margin-bottom: 0.5rem;
    flex-wrap: wrap;
}

.line-num {
    font-family: monospace;
    color: #6b7280;
    font-size: 0.85rem;
}

.severity-badge {
    padding: 0.2rem 0.5rem;
    border-radius: 4px;
    font-size: 0.7rem;
    font-weight: 600;
}

.severity-badge.error { background: var(--color-error); color: white; }
.severity-badge.warning { background: var(--color-warning); color: white; }
.severity-badge.info { background: var(--color-info); color: white; }

.rule-id-small {
    font-family: monospace;
    font-size: 0.8rem;
    color: #8b5cf6;
}

.issue-message {
    color: #374151;
}

.no-issues {
    text-align: center;
    padding: 2rem;
    color: var(--color-success);
    font-size: 1.2rem;
}

/* Statistics */
.statistics-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
    gap: 1.5rem;
}

.chart-container {
    background: white;
    border-radius: 8px;
    padding: 1.5rem;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

.chart-container h3 {
    margin-bottom: 1rem;
    color: #374151;
}

/* Rule Documentation Modal */
.rule-docs-modal {
    display: none;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.5);
    z-index: 1000;
    align-items: center;
    justify-content: center;
}

.rule-docs-modal.show { display: flex; }

.rule-docs-modal-content {
    background: white;
    border-radius: 12px;
    max-width: 800px;
    max-height: 80vh;
    width: 90%;
    overflow: hidden;
    display: flex;
    flex-direction: column;
}

.rule-docs-modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem 1.5rem;
    border-bottom: 1px solid #e5e7eb;
    background: #8b5cf6;
    color: white;
}

.rule-docs-modal-header h2 {
    font-size: 1.2rem;
}

.rule-docs-close {
    background: none;
    border: none;
    font-size: 1.5rem;
    cursor: pointer;
    color: white;
}

.rule-docs-modal-body {
    padding: 1.5rem;
    overflow-y: auto;
    line-height: 1.8;
}

.rule-docs-modal-body h1 { font-size: 1.5rem; margin-bottom: 1rem; color: #8b5cf6; }
.rule-docs-modal-body h2 { font-size: 1.2rem; margin: 1rem 0 0.5rem; color: #374151; }
.rule-docs-modal-body p { margin-bottom: 1rem; }
.rule-docs-modal-body code {
    background: #f3f4f6;
    padding: 0.2rem 0.4rem;
    border-radius: 4px;
    font-family: monospace;
}
.rule-docs-modal-body pre {
    background: #1f2937;
    color: #f9fafb;
    padding: 1rem;
    border-radius: 8px;
    overflow-x: auto;
    margin: 1rem 0;
}

/* Footer */
footer {
    text-align: center;
    padding: 2rem 0;
    margin-top: 2rem;
    border-top: 1px solid #e5e7eb;
    color: #6b7280;
}

/* Hidden class for filtering */
.hidden { display: none !important; }
</style>"""

    def _get_scripts(self) -> str:
        """Get embedded JavaScript."""
        return """<script>
// Tab switching
document.querySelectorAll('.tab-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
        document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
        btn.classList.add('active');
        document.getElementById(btn.dataset.tab).classList.add('active');
    });
});

// Severity filtering
document.querySelectorAll('.filter-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        btn.classList.toggle('active');
        applyFilters();
    });
});

function applyFilters() {
    const activeFilters = Array.from(document.querySelectorAll('.filter-btn.active'))
        .map(btn => btn.dataset.severity);
    
    document.querySelectorAll('.issue').forEach(issue => {
        const severity = issue.dataset.severity;
        if (activeFilters.includes(severity)) {
            issue.classList.remove('hidden');
        } else {
            issue.classList.add('hidden');
        }
    });
}

// Expand/collapse controls
document.querySelectorAll('.expand-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        const action = btn.dataset.action;
        const target = btn.dataset.target;
        const container = document.getElementById(target);
        
        if (action === 'expand-all') {
            container.querySelectorAll('details').forEach(d => d.open = true);
        } else if (action === 'collapse-all') {
            container.querySelectorAll('details').forEach(d => d.open = false);
        } else if (action === 'expand-level1') {
            container.querySelectorAll('.category-section').forEach(d => d.open = true);
            container.querySelectorAll('.rule-section').forEach(d => d.open = true);
            container.querySelectorAll('.rule-file-section').forEach(d => d.open = false);
        } else if (action === 'collapse-level1') {
            container.querySelectorAll('.category-section').forEach(d => d.open = true);
            container.querySelectorAll('.rule-section').forEach(d => d.open = false);
        }
    });
});

// Rule documentation modal
const ruleDocsData = JSON.parse(document.getElementById('rule-docs-data').textContent);

document.querySelectorAll('.rule-help-link').forEach(link => {
    link.addEventListener('click', (e) => {
        e.preventDefault();
        const ruleId = link.dataset.ruleId;
        showRuleDocsModal(ruleId);
    });
});

function showRuleDocsModal(ruleId) {
    const modal = document.getElementById('rule-docs-modal');
    const title = document.getElementById('rule-docs-title');
    const body = document.getElementById('rule-docs-body');
    
    title.textContent = ruleId;
    
    const content = ruleDocsData[ruleId] || 'No documentation available.';
    body.innerHTML = simpleMarkdown(content);
    
    modal.classList.add('show');
}

function closeRuleDocsModal() {
    document.getElementById('rule-docs-modal').classList.remove('show');
}

// Close modal on outside click
document.getElementById('rule-docs-modal').addEventListener('click', (e) => {
    if (e.target.id === 'rule-docs-modal') {
        closeRuleDocsModal();
    }
});

// Simple markdown renderer
function simpleMarkdown(text) {
    return text
        .replace(/^### (.*$)/gm, '<h3>$1</h3>')
        .replace(/^## (.*$)/gm, '<h2>$1</h2>')
        .replace(/^# (.*$)/gm, '<h1>$1</h1>')
        .replace(/\\*\\*(.*?)\\*\\*/g, '<strong>$1</strong>')
        .replace(/\\*(.*?)\\*/g, '<em>$1</em>')
        .replace(/`([^`]+)`/g, '<code>$1</code>')
        .replace(/```([\\s\\S]*?)```/g, '<pre>$1</pre>')
        .replace(/\\n/g, '<br>');
}

// Initialize charts when statistics tab is shown
document.querySelector('[data-tab="statistics"]').addEventListener('click', initCharts);

let chartsInitialized = false;
function initCharts() {
    if (chartsInitialized) return;
    chartsInitialized = true;
    
    // Severity chart
    if (typeof severityData !== 'undefined') {
        new Chart(document.getElementById('severity-chart'), {
            type: 'doughnut',
            data: {
                labels: severityData.labels,
                datasets: [{
                    data: severityData.data,
                    backgroundColor: severityData.colors
                }]
            },
            options: {
                responsive: true,
                plugins: { legend: { position: 'bottom' } }
            }
        });
    }
    
    // Top rules chart
    if (typeof topRulesData !== 'undefined') {
        new Chart(document.getElementById('top-rules-chart'), {
            type: 'bar',
            data: {
                labels: topRulesData.labels,
                datasets: [{
                    label: 'Issues',
                    data: topRulesData.data,
                    backgroundColor: '#8b5cf6'
                }]
            },
            options: {
                responsive: true,
                indexAxis: 'y',
                plugins: { legend: { display: false } }
            }
        });
    }
    
    // Category chart
    if (typeof categoryData !== 'undefined') {
        new Chart(document.getElementById('category-chart'), {
            type: 'pie',
            data: {
                labels: categoryData.labels,
                datasets: [{
                    data: categoryData.data,
                    backgroundColor: [
                        '#8b5cf6', '#3b82f6', '#10b981', '#f59e0b', 
                        '#ef4444', '#ec4899', '#6366f1', '#14b8a6'
                    ]
                }]
            },
            options: {
                responsive: true,
                plugins: { legend: { position: 'bottom' } }
            }
        });
    }
    
    // Top files chart
    if (typeof topFilesData !== 'undefined') {
        new Chart(document.getElementById('top-files-chart'), {
            type: 'bar',
            data: {
                labels: topFilesData.labels,
                datasets: [{
                    label: 'Issues',
                    data: topFilesData.data,
                    backgroundColor: '#3b82f6'
                }]
            },
            options: {
                responsive: true,
                indexAxis: 'y',
                plugins: { legend: { display: false } }
            }
        });
    }
}
</script>"""
