# -*- coding: utf-8 -*-
"""
Lint engine - orchestrates rule execution and result collection.

This module provides the main engine that coordinates file parsing,
rule execution, and result aggregation.

Copyright (c) 2024-2026 Eduardo Correia <ecorreia@apliant.com.br>

This file is part of bake_linter. It is free software, licensed under the
GNU Lesser General Public License v3.0 or later. See COPYING.LESSER and
COPYING for details.

SPDX-License-Identifier: LGPL-3.0-or-later
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Optional, Set, Iterable, TYPE_CHECKING

from bake_linter.core.models import (
    LintResult, LintSummary, Severity, FileContext, 
    VariableAssignment, RuleConfig,
    INLINE_SUPPRESSION_PATTERN,  # re-exported for existing importers
)
from bake_linter.core.registry import get_registry

if TYPE_CHECKING:
    from bake_linter.rules.base import BaseRule


# Regex patterns for parsing BitBake files
VAR_ASSIGNMENT_PATTERN = re.compile(
    r'^(?P<name>[A-Z][A-Z0-9_]*)(?::(?P<override>[a-z0-9_-]+))?\s*'
    r'(?P<operator>\?\?=|\?=|:=|\.=|=\.|=\+|\+=|=)\s*'
    r'(?P<value>.*)$'
)

AUTOGEN_MARKERS = [
    "# Auto-generated",
    "# Automatically generated",
    "# DO NOT EDIT",
    "# Generated by",
    "# This file is auto-generated",
]


class LintEngine:
    """
    Main linting engine that orchestrates rule execution.
    
    The engine is responsible for:
    - Discovering and loading files to lint
    - Parsing files into FileContext objects
    - Running enabled rules against each file
    - Collecting and aggregating results
    
    Example:
        >>> engine = LintEngine()
        >>> engine.configure(enabled_rules=["LICENSE001", "MANDATORY001"])
        >>> results = engine.lint_files([Path("recipes/")])
        >>> summary = engine.get_summary()
    """

    # File extensions to process
    SUPPORTED_EXTENSIONS = {".bb", ".inc"}
    SUPPORTED_SUFFIXES = {".bbappend"}

    def __init__(self):
        """Initialize the lint engine."""
        self._registry = get_registry()
        self._rule_configs: Dict[str, RuleConfig] = {}
        self._enabled_rules: Optional[Set[str]] = None  # None = all enabled
        self._disabled_rules: Set[str] = set()
        self._results: List[LintResult] = []
        self._files_scanned: int = 0
        self._skipped_files: List[str] = []
        self._severity_override: Optional[Severity] = None
        self._skip_autogenerated: bool = True
        self._exclude_patterns: List[str] = []

    def configure(
        self,
        rule_configs: Optional[Dict[str, RuleConfig]] = None,
        enabled_rules: Optional[List[str]] = None,
        disabled_rules: Optional[List[str]] = None,
        enabled_groups: Optional[List[str]] = None,
        disabled_groups: Optional[List[str]] = None,
        severity_override: Optional[Severity] = None,
        skip_autogenerated: bool = True,
        exclude_patterns: Optional[List[str]] = None,
    ) -> None:
        """
        Configure the lint engine.
        
        Args:
            rule_configs: Configuration for individual rules
            enabled_rules: Explicitly enable only these rules (overrides config)
            disabled_rules: Explicitly disable these rules (overrides config)
            enabled_groups: Enable all rules in these groups
            disabled_groups: Disable all rules in these groups
            severity_override: Override severity for all rules
            skip_autogenerated: Skip autogenerated files
            exclude_patterns: Glob patterns to exclude files/directories
        """
        if rule_configs:
            self._rule_configs = rule_configs

        # Handle explicit rule enables/disables
        if enabled_rules is not None:
            self._enabled_rules = set(enabled_rules)
        
        if disabled_rules:
            self._disabled_rules = set(disabled_rules)

        # Handle group enables/disables
        if enabled_groups:
            if self._enabled_rules is None:
                self._enabled_rules = set()
            for group in enabled_groups:
                for rule_cls in self._registry.get_rules_by_group(group):
                    self._enabled_rules.add(rule_cls.rule_id)

        if disabled_groups:
            for group in disabled_groups:
                for rule_cls in self._registry.get_rules_by_group(group):
                    self._disabled_rules.add(rule_cls.rule_id)

        self._severity_override = severity_override
        self._skip_autogenerated = skip_autogenerated
        
        if exclude_patterns:
            self._exclude_patterns = list(exclude_patterns)

    def _is_file_excluded(self, path: Path) -> bool:
        """Check if a file matches any exclude pattern."""
        import fnmatch
        
        path_str = str(path)
        for pattern in self._exclude_patterns:
            # Check both the full path and just the filename/relative path
            if fnmatch.fnmatch(path_str, pattern):
                return True
            if fnmatch.fnmatch(path_str, f"*/{pattern}"):
                return True
            if fnmatch.fnmatch(path.name, pattern):
                return True
            # Also check if any parent directory matches (for excluding directories)
            for parent in path.parents:
                if fnmatch.fnmatch(parent.name, pattern.rstrip('/')):
                    return True
        return False

    def _is_rule_enabled(self, rule_id: str) -> bool:
        """Check if a rule is enabled based on configuration."""
        # CLI disabled rules always take precedence
        if rule_id in self._disabled_rules:
            return False

        # If explicit enabled list, rule must be in it
        if self._enabled_rules is not None:
            return rule_id in self._enabled_rules

        # Check rule config
        if rule_id in self._rule_configs:
            return self._rule_configs[rule_id].enabled

        # Check rule default
        rule_cls = self._registry.get_rule(rule_id)
        if rule_cls:
            return rule_cls.enabled_by_default

        return True

    def _get_rule_severity(self, rule_cls: type) -> Severity:
        """Get the effective severity for a rule."""
        if self._severity_override:
            return self._severity_override
        
        rule_id = rule_cls.rule_id
        if rule_id in self._rule_configs:
            config = self._rule_configs[rule_id]
            if config.severity:
                return config.severity

        return rule_cls.default_severity

    def _collect_files(self, paths: Iterable[Path]) -> List[Path]:
        """
        Collect all BitBake files from the given paths.
        
        Args:
            paths: Files or directories to scan
            
        Returns:
            List of file paths to lint
        """
        files: List[Path] = []
        
        for path in paths:
            if path.is_file():
                if self._is_supported_file(path) and not self._is_file_excluded(path):
                    files.append(path)
            elif path.is_dir():
                for child in sorted(path.rglob("*")):
                    if child.is_file() and self._is_supported_file(child) and not self._is_file_excluded(child):
                        files.append(child)
        
        # Deterministic order
        return sorted(files)

    def _is_supported_file(self, path: Path) -> bool:
        """Check if a file is a supported BitBake file."""
        if path.suffix in self.SUPPORTED_EXTENSIONS:
            return True
        for suffix in self.SUPPORTED_SUFFIXES:
            if path.name.endswith(suffix):
                return True
        return False

    def _parse_file(self, path: Path) -> Optional[FileContext]:
        """
        Parse a BitBake file into a FileContext.
        
        Args:
            path: Path to the file
            
        Returns:
            FileContext or None if file couldn't be read
        """
        try:
            content = path.read_text(encoding="utf-8", errors="replace")
        except (OSError, IOError) as e:
            self._skipped_files.append(f"{path}: {e}")
            return None

        lines = content.splitlines()
        
        # Check for autogenerated markers
        is_autogenerated = False
        for marker in AUTOGEN_MARKERS:
            if any(marker.lower() in line.lower() for line in lines[:10]):
                is_autogenerated = True
                break

        # Parse variable assignments (FileContext parses inline suppressions)
        variables: Dict[str, List[VariableAssignment]] = {}
        parse_errors: List[str] = []
        
        for line_num, line in enumerate(lines, start=1):
            stripped = line.strip()
            
            # Skip comments and empty lines for variable parsing
            if not stripped or stripped.startswith("#"):
                continue
            
            # Try to match variable assignment
            match = VAR_ASSIGNMENT_PATTERN.match(stripped)
            if match:
                var_name = match.group("name")
                var_value = match.group("value").strip()
                operator = match.group("operator")
                override = match.group("override")
                
                # Handle quoted values
                if var_value.startswith('"') and var_value.endswith('"'):
                    var_value = var_value[1:-1]
                elif var_value.startswith("'") and var_value.endswith("'"):
                    var_value = var_value[1:-1]
                
                assignment = VariableAssignment(
                    name=var_name,
                    value=var_value,
                    line=line_num,
                    operator=operator,
                    is_override=bool(override),
                    override=override,
                )
                
                if var_name not in variables:
                    variables[var_name] = []
                variables[var_name].append(assignment)

        return FileContext(
            path=path,
            content=content,
            lines=lines,
            variables=variables,
            is_autogenerated=is_autogenerated,
            parse_errors=parse_errors,
        )

    def _get_enabled_rules(self) -> List["BaseRule"]:
        """Get instances of all enabled rules."""
        rules = []
        
        for rule_id, rule_cls in self._registry.get_all_rules().items():
            if self._is_rule_enabled(rule_id):
                # Get rule-specific options from config
                options = {}
                if rule_id in self._rule_configs:
                    options = self._rule_configs[rule_id].options
                
                # Instantiate rule with effective severity
                severity = self._get_rule_severity(rule_cls)
                rule = rule_cls(severity_override=severity, options=options)
                rules.append(rule)
        
        return rules

    def lint_files(self, paths: List[Path]) -> List[LintResult]:
        """
        Lint all files in the given paths.
        
        Args:
            paths: List of files or directories to lint
            
        Returns:
            List of all lint results
        """
        self._results = []
        self._files_scanned = 0
        self._skipped_files = []
        
        # Discover rules if not already done
        self._registry.discover_rules()
        
        # Collect files
        files = self._collect_files(paths)
        
        # Get enabled rules
        rules = self._get_enabled_rules()
        
        if not rules:
            return []

        # Process each file
        for file_path in files:
            context = self._parse_file(file_path)
            if context is None:
                continue
            
            self._files_scanned += 1
            
            # Skip autogenerated files if configured
            if self._skip_autogenerated and context.is_autogenerated:
                continue
            
            # Run each rule that applies to this kind of file
            for rule in rules:
                if not rule.is_applicable(context):
                    continue
                try:
                    results = rule.check(context)
                    # Drop suppressed issues: create_result returns None for
                    # them, and results built any other way are checked here
                    results = [
                        r for r in results
                        if r is not None and not context.is_suppressed(r.rule_id, r.line)
                    ]
                    self._results.extend(results)
                except Exception as e:
                    # Don't let a rule failure break the entire lint
                    self._results.append(LintResult(
                        rule_id=rule.rule_id,
                        file=file_path,
                        severity=Severity.ERROR,
                        message=f"Rule {rule.rule_id} failed: {e}",
                        rule_name=rule.name,
                    ))

        # Sort results for consistent output
        self._results.sort()
        
        return self._results

    def get_results(self) -> List[LintResult]:
        """Get all lint results from the last run."""
        return self._results

    def get_summary(self) -> LintSummary:
        """Get summary statistics for the last lint run."""
        rules = self._get_enabled_rules()
        return LintSummary.from_results(
            results=self._results,
            files_scanned=self._files_scanned,
            rules_executed=len(rules),
            skipped_files=self._skipped_files,
        )

    def clear(self) -> None:
        """Clear results and reset counters."""
        self._results = []
        self._files_scanned = 0
        self._skipped_files = []
